included:
  - fichero-swiftui/fichero-swiftui

excluded:
  - fichero-swiftui/fichero-swiftui/Services/*Generated.swift
  - fichero-swiftui/fichero-swiftui/fichero-api-client
  - fichero-swiftui/fichero-swiftui/Views/Library/ImageViewer
