# Configuration for execution modes
# This file is used by fichero_cli.py to control how steps are executed

# Hardware detection and optimization
hardware:
  auto_detect: false  # Disable automatic hardware detection
  device: "cpu"       # Force MPS for Apple Silicon
  force_cpu: false     # Force CPU usage even if GPU is available

# System-specific configurations
system_configs:
  cuda:
    # GPU tasks
    crop:
      workers: 2  # Reduced from 4 to 2 workers
    split:
      workers: 2  # Reduced from 4 to 2 workers
    transcribe_qwen_max:
      workers: 1  # Reduced from 2 to 1 worker
    transcribe_qwen_7b:
      workers: 1  # Reduced from 2 to 1 worker
    transcribe_lmstudio:
      workers: 1  # Reduced from 2 to 1 worker
    # CPU tasks
    rotate:
      workers: 4
    enhance:
      workers: 4
    remove_background:
      workers: 4
    segment:
      workers: 4
  
  mps:  # Apple Silicon M1 16GB
    # GPU tasks
    crop:
      workers: 1  # Keep at 1 worker for MPS
    split:
      workers: 1  # Keep at 1 worker for MPS
    crop_cpu:
      workers: 3  # CPU fallback with more workers
    split_cpu:
      workers: 4  # CPU fallback with more workers
    transcribe_qwen_max:
      workers: 1
    transcribe_qwen_7b:
      workers: 1
    transcribe_lmstudio:
      workers: 1
    # CPU tasks
    rotate:
      workers: 3
    enhance:
      workers: 3
    remove_background:
      workers: 3
    segment:
      workers: 3
  
  cpu:  # CPU-only configuration
    crop:
      workers: 4
    split:
      workers: 4  # Can use more workers as split is less intensive
    transcribe_qwen_max:
      workers: 1
    transcribe_qwen_7b:
      workers: 1
    transcribe_lmstudio:
      workers: 1
    rotate:
      workers: 4
    enhance:
      workers: 3
    remove_background:
      workers: 3
    segment:
      workers: 3

# Steps that should run sequentially (one file at a time)
sequential_steps:
  - prepare_images          # Initial file preparation
  - convert_to_jpg         # Format conversion
  - build_documents_manifest  # Single operation on entire folder
  - recombine_segments     # Needs all segments before combining
  - recombine_segments_qwen_max
  - fuzzy_clean           # Post-processing of all files
  - convert_to_word       # Final conversion step

# Steps that can run concurrently (multiple files processed by worker pool)
concurrent_steps:
  - crop                  # Image processing
  - split                 # Image processing
  - rotate                # Image processing
  - enhance               # Image processing
  - remove_background     # Image processing
  - segment               # Image processing
  - transcribe_qwen_7b
  - transcribe_qwen_max
  - transcribe_lmstudio 