"""One answer to "who asserted this row, and may a tool overwrite it?" (#4415).

Re-running an extraction stage regenerates over rows the user already fixed.
Entity merges, corrected claims and fixed boundaries are durable statements
that the extractor got something wrong; regenerating over them destroys the
most valuable data in the library — the human judgement the machine could not
supply. This module is the single check that stops that.

Shape borrowed deliberately from #3322 step 5b (a user-set date surviving
re-extraction), because two mechanisms for one concept is the defect class
this project keeps hitting:

- **The rule lives on the row it governs.** ``metadata["curation"]`` on the
  KnowledgeEntity / KnowledgeClaim itself — not a side table that must be kept
  in agreement with the row.
- **The stage still RUNS; it may not overwrite.** An improved extractor is
  still allowed to compute and to *offer* a better answer.
- **Disagreement is recorded, never silently resolved.** Neither the user's
  value nor the new candidate is discarded: the candidate lands in
  ``extraction_conflict`` and is surfaced in the run summary. A disagreement
  the user cannot see is a fact destroyed.

Why not key the check on ``curation_state``: it holds the *value*, not the
*provenance of the value*. ``merge_dedup_only`` writes ``rejected`` exactly as
a human route does, so ``curation_state`` alone cannot tell tool output from
user work — it would refuse to refresh generated rows and happily destroy
curated ones the moment the two shapes coincide.

Provenance that predates this marker is recovered from the audit tables, which
workflow tools never write (``MutationLog``, ``EntityMergeAudit``,
``ClaimMergeAudit`` are written by API routes only) — so an audit row against
an id means a human-facing route touched it. Since #4415's audit fixes
(e85d7b5bd) every such record names its actor, and agent curation is audited
too, so an agent's edits are protected exactly like a person's: per the
project's "AI = a USER account via audited MCP tools" rule, an agent's
correction is a correction.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any

from fichero_server.core.timeutil import utc_now

# Key under `metadata` on the row the record governs. One mechanism.
CURATION_KEY = "curation"
CONFLICT_KEY = "extraction_conflict"


class CurationSource(str, Enum):
    """Who asserted the current value of a curated field."""

    tool = "tool"
    """Generated by a workflow tool. Free to refresh."""

    user = "user"
    """Asserted by a person. Never overwrite."""

    agent = "agent"
    """Asserted by an agent user account via an audited route. Never overwrite."""

    unknown = "unknown"
    """No provenance recorded and none derivable. Never overwrite; surface it.

    Distinct from ``tool``: "we know a tool wrote this" and "we cannot tell who
    wrote this" are different claims, and collapsing them is what silently
    destroys curation. Callers resolve ``unknown`` against the audit tables
    (:func:`resolve_curation`) rather than defaulting it either way.
    """


#: Sources a workflow tool may not overwrite. ``unknown`` is in this set on
#: purpose: when we cannot establish that a tool produced a row, the safe and
#: honest move is to leave it and say so, never to regenerate over it.
PROTECTED_SOURCES = frozenset({CurationSource.user, CurationSource.agent, CurationSource.unknown})


@dataclass(frozen=True)
class CurationRecord:
    """Provenance of a row's curated fields, and why we believe it."""

    source: CurationSource
    actor: str | None = None
    asserted_at: str | None = None
    basis: str | None = None
    """How this verdict was reached — 'stamped', 'audit-evidence', … .

    Carried so a skip or a refusal can explain itself on demand rather than
    being an unexplained absence.
    """

    @property
    def is_protected(self) -> bool:
        return self.source in PROTECTED_SOURCES


def read_curation(row: Any) -> CurationRecord:
    """Read the provenance marker off a row.

    Returns ``unknown`` when the row carries no marker — absence of evidence is
    never reported as evidence of tool authorship.
    """
    metadata = getattr(row, "metadata", None)
    if not isinstance(metadata, dict):
        return CurationRecord(CurationSource.unknown, basis="no-metadata")

    raw = metadata.get(CURATION_KEY)
    if not isinstance(raw, dict):
        return CurationRecord(CurationSource.unknown, basis="unstamped")

    try:
        source = CurationSource(raw.get("source"))
    except ValueError:
        # An unrecognised source is not a licence to overwrite. Prefer an
        # honest "cannot tell" over a guess (no-silent-fallback).
        return CurationRecord(CurationSource.unknown, basis="unrecognised-source")

    return CurationRecord(
        source=source,
        actor=raw.get("actor"),
        asserted_at=raw.get("asserted_at"),
        basis=raw.get("basis") or "stamped",
    )


def resolve_curation(row: Any, *, audited_ids: frozenset[str] | set[str]) -> CurationRecord:
    """The check, built once — #4415 and #4387 both ask this question.

    #4387 asks "does this output already exist for this target?"; #4415 asks
    "is it still current, and may I overwrite it?". The second contains the
    first, so they share one function: two would disagree, and a surface
    offering a run the runner then skips is precisely that contradiction.

    An unstamped row is resolved against ``audited_ids`` — the ids that any
    human-facing route has recorded a mutation or merge against (see
    :func:`audited_row_ids`). Evidence present means a person or an agent
    touched it, so it is curated. Evidence absent, for a row in a library where
    audit logging is active, means no human-facing route ever touched it, so a
    tool produced it and it may be refreshed.
    """
    record = read_curation(row)
    if record.source is not CurationSource.unknown:
        return record

    row_id = getattr(row, "id", None)
    if row_id and row_id in audited_ids:
        return CurationRecord(CurationSource.user, basis="audit-evidence")

    return CurationRecord(CurationSource.tool, basis="no-audit-evidence")


#: Actors that are the pipeline itself rather than someone curating through it.
#: ``merge_dedup_only`` drives the entity/claim merge *routes* with
#: ``ActionContext(actor="workflow")``, so those routes do write audit rows —
#: the premise "no workflow tool writes an audit row" is false for merges. An
#: audit row from one of these actors is the tool's own output and must not be
#: read back as a user's correction, or the tool freezes its own results after
#: one run and reports them as curated.
MACHINE_ACTORS = frozenset({"workflow", "system"})


def audited_row_ids(db, row_ids: set[str]) -> frozenset[str]:
    """Ids among ``row_ids`` that a *person or agent* has audited.

    Batched deliberately: the alternative is a query per row, and this runs
    over every entity and claim scoped to a catalogue run.

    Rows audited only by :data:`MACHINE_ACTORS` are excluded — presence has to
    mean "someone curated this", not merely "something wrote a record".
    """
    if not row_ids:
        return frozenset()

    # Imported here rather than at module scope to keep this module importable
    # without the model/db graph (mirrors the layering note in merge_dedup_only).
    from fichero_server.models.knowledge import (
        ClaimMergeAudit,
        EntityMergeAudit,
        MutationLog,
    )

    audited: set[str] = set()

    def _curated_by_someone(record: Any) -> bool:
        return (getattr(record, "created_by", None) or "human") not in MACHINE_ACTORS

    for log in db.query(MutationLog):
        if log.entity_id in row_ids and _curated_by_someone(log):
            audited.add(log.entity_id)

    for audit in db.query(EntityMergeAudit):
        if not _curated_by_someone(audit):
            continue
        if audit.target_entity_id in row_ids:
            audited.add(audit.target_entity_id)
        for source_id in audit.source_entity_ids or []:
            if source_id in row_ids:
                audited.add(source_id)

    for audit in db.query(ClaimMergeAudit):
        if not _curated_by_someone(audit):
            continue
        if audit.target_claim_id in row_ids:
            audited.add(audit.target_claim_id)
        for source_id in audit.source_claim_ids or []:
            if source_id in row_ids:
                audited.add(source_id)

    return frozenset(audited)


def _next_metadata(row: Any) -> dict:
    """Copy the row's metadata so callers can compare before/after.

    A copy rather than in-place mutation: the caller decides whether anything
    changed, and so writes only when it did (that is what makes a re-run over
    settled rows a genuine no-op rather than a churn of identical saves).
    """
    metadata = getattr(row, "metadata", None)
    return dict(metadata) if isinstance(metadata, dict) else {}


def stamp(
    row: Any,
    *,
    source: CurationSource,
    actor: str | None = None,
    basis: str | None = None,
) -> bool:
    """Record who asserted this row. Returns True if the row changed.

    Stamping is what stops the audit-table derivation being repeated forever:
    a resolved verdict is written down once, with its basis, and is thereafter
    read straight off the row.
    """
    metadata = _next_metadata(row)
    existing = metadata.get(CURATION_KEY)
    marker = {
        "source": source.value,
        "actor": actor,
        "asserted_at": utc_now().isoformat(),
        "basis": basis or "stamped",
    }
    # Preserve an outstanding conflict: stamping provenance is not the same
    # act as resolving a disagreement, and dropping it here would silently
    # discard the extractor's candidate.
    if isinstance(existing, dict) and CONFLICT_KEY in existing:
        marker[CONFLICT_KEY] = existing[CONFLICT_KEY]

    if isinstance(existing, dict):
        # `asserted_at` alone must not count as a change, or every run rewrites
        # every row and "already done" becomes unobservable.
        comparable_old = {k: v for k, v in existing.items() if k != "asserted_at"}
        comparable_new = {k: v for k, v in marker.items() if k != "asserted_at"}
        if comparable_old == comparable_new:
            return False
        marker["asserted_at"] = existing.get("asserted_at") or marker["asserted_at"]

    metadata[CURATION_KEY] = marker
    row.metadata = metadata
    return True


def record_conflict(row: Any, *, proposal: dict | None, reason: str) -> bool:
    """Record that a tool disagreed with a curated row. Returns True if changed.

    The tool's proposal is kept in full. Neither value is discarded: the user's
    stands as the row's value, the tool's is preserved beside it so the
    disagreement can be surfaced and decided rather than silently resolved in
    either direction.
    """
    metadata = _next_metadata(row)
    existing = metadata.get(CURATION_KEY)
    marker = dict(existing) if isinstance(existing, dict) else {"source": CurationSource.unknown.value}

    conflict = {"proposal": proposal, "reason": reason, "found_at": utc_now().isoformat()}

    prior = marker.get(CONFLICT_KEY)
    if isinstance(prior, dict) and prior.get("proposal") == proposal and prior.get("reason") == reason:
        # Same disagreement as last run — already recorded. Re-stamping the
        # timestamp would make an unchanged row look freshly touched.
        return False

    marker[CONFLICT_KEY] = conflict
    metadata[CURATION_KEY] = marker
    row.metadata = metadata
    return True


def clear_conflict(row: Any) -> bool:
    """Drop a recorded disagreement once it no longer holds. True if changed.

    Agreement clears a stale conflict — otherwise a disagreement the extractor
    has since abandoned would haunt the row forever.
    """
    metadata = _next_metadata(row)
    existing = metadata.get(CURATION_KEY)
    if not isinstance(existing, dict) or CONFLICT_KEY not in existing:
        return False

    marker = {k: v for k, v in existing.items() if k != CONFLICT_KEY}
    metadata[CURATION_KEY] = marker
    row.metadata = metadata
    return True


def has_conflict(row: Any) -> bool:
    metadata = getattr(row, "metadata", None)
    if not isinstance(metadata, dict):
        return False
    marker = metadata.get(CURATION_KEY)
    return isinstance(marker, dict) and CONFLICT_KEY in marker
