"""One answer to "who asserted this row, and may a tool overwrite it?" (#4415).

Re-running an extraction stage regenerates over rows the user already fixed.
Entity merges, corrected claims and fixed boundaries are durable statements
that the extractor got something wrong; regenerating over them destroys the
most valuable data in the library — the human judgement the machine could not
supply. This module is the single check that stops that.

Shape borrowed deliberately from #3322 step 5b (a user-set date surviving
re-extraction), because two mechanisms for one concept is the defect class
this project keeps hitting:

- **The rule lives on the row it governs.** ``metadata["curation"]`` on the
  KnowledgeEntity / KnowledgeClaim itself — not a side table that must be kept
  in agreement with the row.
- **The stage still RUNS; it may not overwrite.** An improved extractor is
  still allowed to compute and to *offer* a better answer.
- **What was corrected away from is remembered too** (#4499). A stamp says a
  person asserted the row; it cannot say what they rejected, and a claim's
  dedup key is its text and SVO — the very thing an edit changes. So the
  rejected readings are kept on the row (``superseded``) and an extraction is
  matched against those as well as the current value. Otherwise a re-run
  reproducing the pre-edit reading matches nothing, is filed as a new claim,
  and the archive asserts both the correction and the thing it corrected.
- **Disagreement is recorded, never silently resolved.** Neither the user's
  value nor the new candidate is discarded: the candidate lands in
  ``extraction_conflict`` and is surfaced in the run summary. A disagreement
  the user cannot see is a fact destroyed.

Why not key the check on ``curation_state``: it holds the *value*, not the
*provenance of the value*. ``merge_dedup_only`` writes ``rejected`` exactly as
a human route does, so ``curation_state`` alone cannot tell tool output from
user work — it would refuse to refresh generated rows and happily destroy
curated ones the moment the two shapes coincide.

Provenance that predates this marker is recovered from the audit tables, which
workflow tools never write (``MutationLog``, ``EntityMergeAudit``,
``ClaimMergeAudit`` are written by API routes only) — so an audit row against
an id means a human-facing route touched it. Since #4415's audit fixes
(e85d7b5bd) every such record names its actor, and agent curation is audited
too, so an agent's edits are protected exactly like a person's: per the
project's "AI = a USER account via audited MCP tools" rule, an agent's
correction is a correction.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any

from fichero_server.core.timeutil import utc_now

# Key under `metadata` on the row the record governs. One mechanism.
CURATION_KEY = "curation"
CONFLICT_KEY = "extraction_conflict"
SUPERSEDED_KEY = "superseded"


class CurationSource(str, Enum):
    """Who asserted the current value of a curated field."""

    tool = "tool"
    """Generated by a workflow tool. Free to refresh."""

    user = "user"
    """Asserted by a person. Never overwrite."""

    agent = "agent"
    """Asserted by an agent user account via an audited route. Never overwrite."""

    unknown = "unknown"
    """No provenance recorded and none derivable. Never overwrite; surface it.

    Distinct from ``tool``: "we know a tool wrote this" and "we cannot tell who
    wrote this" are different claims, and collapsing them is what silently
    destroys curation. Callers resolve ``unknown`` against the audit tables
    (:func:`resolve_curation`) rather than defaulting it either way.
    """

    @property
    def is_curated(self) -> bool:
        """True when a workflow tool may not overwrite a value from here."""
        return self in PROTECTED_SOURCES


#: Sources a workflow tool may not overwrite. ``unknown`` is in this set on
#: purpose: when we cannot establish that a tool produced a row, the safe and
#: honest move is to leave it and say so, never to regenerate over it.
PROTECTED_SOURCES = frozenset({CurationSource.user, CurationSource.agent, CurationSource.unknown})


@dataclass(frozen=True)
class CurationRecord:
    """Provenance of a row's curated fields, and why we believe it."""

    source: CurationSource
    actor: str | None = None
    asserted_at: str | None = None
    basis: str | None = None
    """How this verdict was reached — 'stamped', 'audit-evidence', … .

    Carried so a skip or a refusal can explain itself on demand rather than
    being an unexplained absence.
    """

    @property
    def is_protected(self) -> bool:
        return self.source in PROTECTED_SOURCES


def marker_field(row: Any) -> str:
    """Which field on ``row`` holds its curation marker.

    Entities, claims and documents carry ``metadata``; ``Artifact`` has only
    ``data``. One accessor rather than a per-call-site convention, so a caller
    cannot write the marker where the reader will not look for it.
    """
    return "metadata" if hasattr(row, "metadata") else "data"


def read_curation(row: Any) -> CurationRecord:
    """Read the provenance marker off a row.

    Returns ``unknown`` when the row carries no marker — absence of evidence is
    never reported as evidence of tool authorship.
    """
    metadata = getattr(row, marker_field(row), None)
    if not isinstance(metadata, dict):
        return CurationRecord(CurationSource.unknown, basis="no-metadata")

    raw = metadata.get(CURATION_KEY)
    if not isinstance(raw, dict):
        return CurationRecord(CurationSource.unknown, basis="unstamped")

    try:
        source = CurationSource(raw.get("source"))
    except ValueError:
        # An unrecognised source is not a licence to overwrite. Prefer an
        # honest "cannot tell" over a guess (no-silent-fallback).
        return CurationRecord(CurationSource.unknown, basis="unrecognised-source")

    return CurationRecord(
        source=source,
        actor=raw.get("actor"),
        asserted_at=raw.get("asserted_at"),
        basis=raw.get("basis") or "stamped",
    )


def resolve_curation(row: Any, *, audited_ids: frozenset[str] | set[str]) -> CurationRecord:
    """The check, built once — #4415 and #4387 both ask this question.

    #4387 asks "does this output already exist for this target?"; #4415 asks
    "is it still current, and may I overwrite it?". The second contains the
    first, so they share one function: two would disagree, and a surface
    offering a run the runner then skips is precisely that contradiction.

    An unstamped row is resolved against ``audited_ids`` — the ids that any
    human-facing route has recorded a mutation or merge against (see
    :func:`audited_row_ids`). Evidence present means a person or an agent
    touched it, so it is curated. Evidence absent, for a row in a library where
    audit logging is active, means no human-facing route ever touched it, so a
    tool produced it and it may be refreshed.
    """
    record = read_curation(row)
    if record.source is not CurationSource.unknown:
        return record

    row_id = getattr(row, "id", None)
    if row_id and row_id in audited_ids:
        return CurationRecord(CurationSource.user, basis="audit-evidence")

    return CurationRecord(CurationSource.tool, basis="no-audit-evidence")


#: Actors that are the pipeline itself rather than someone curating through it.
#: ``merge_dedup_only`` drives the entity/claim merge *routes* with
#: ``ActionContext(actor="workflow")``, so those routes do write audit rows —
#: the premise "no workflow tool writes an audit row" is false for merges. An
#: audit row from one of these actors is the tool's own output and must not be
#: read back as a user's correction, or the tool freezes its own results after
#: one run and reports them as curated.
MACHINE_ACTORS = frozenset({"workflow", "system"})


def audited_row_ids(db, row_ids: set[str]) -> frozenset[str]:
    """Ids among ``row_ids`` that a *person or agent* has audited.

    Batched deliberately: the alternative is a query per row, and this runs
    over every entity and claim scoped to a catalogue run.

    Ceiling worth naming: each table is scanned whole. ``ActionAudit`` grows
    with every audited mutation, so it is the one that will bite first on a
    long-lived library — the upgrade path is an indexed lookup by target id,
    not a cleverer scan. Correctness does not depend on it.

    Rows audited only by :data:`MACHINE_ACTORS` are excluded — presence has to
    mean "someone curated this", not merely "something wrote a record".
    """
    if not row_ids:
        return frozenset()

    # Imported here rather than at module scope to keep this module importable
    # without the model/db graph (mirrors the layering note in merge_dedup_only).
    from fichero_server.models.knowledge import (
        ClaimMergeAudit,
        EntityMergeAudit,
        MutationLog,
    )

    audited: set[str] = set()

    def _curated_by_someone(record: Any) -> bool:
        return (getattr(record, "created_by", None) or "human") not in MACHINE_ACTORS

    for log in db.query(MutationLog):
        if log.entity_id in row_ids and _curated_by_someone(log):
            audited.add(log.entity_id)

    for audit in db.query(EntityMergeAudit):
        if not _curated_by_someone(audit):
            continue
        if audit.target_entity_id in row_ids:
            audited.add(audit.target_entity_id)
        for source_id in audit.source_entity_ids or []:
            if source_id in row_ids:
                audited.add(source_id)

    for audit in db.query(ClaimMergeAudit):
        if not _curated_by_someone(audit):
            continue
        if audit.target_claim_id in row_ids:
            audited.add(audit.target_claim_id)
        for source_id in audit.source_claim_ids or []:
            if source_id in row_ids:
                audited.add(source_id)

    # ActionAudit is the general case the three tables above predate: the
    # registry writes one for EVERY audited action, non-best-effort, naming
    # the actor and the ids it touched (#4485). Artifacts and documents have
    # no MutationLog writer at all, so without this the guard is simply blind
    # to `artifact.update` and `document.update` — every corrected artifact
    # reads as untouched machine output.
    from fichero_server.models import ActionAudit

    for audit in db.query(ActionAudit):
        if (getattr(audit, "actor", None) or "human") in MACHINE_ACTORS:
            continue
        for target_id in audit.target_ids or []:
            if target_id in row_ids:
                audited.add(target_id)

    return frozenset(audited)


#: Where the document route records that a person edited a page's text (#672).
#: Predates this module; folded in rather than reimplemented, so ``llm_base``
#: and Catalogue cannot drift into disagreeing about the same question.
PAGE_CONTENT_USER_EDITED_KEY = "page_content_user_edited_at"


def page_content_is_user_edited(doc: Any) -> bool:
    """True when a person has saved an edit to this document's page_content.

    ``llm_base`` has honoured this since #672; Catalogue wrote the container's
    page_content directly and never asked. One function so "may I overwrite
    this text?" has one answer for every writer.
    """
    metadata = getattr(doc, "metadata", None)
    return bool(isinstance(metadata, dict) and metadata.get(PAGE_CONTENT_USER_EDITED_KEY))


def sweep_replaceable(
    db,
    rows: list,
    *,
    reason: str,
    proposal_for=None,
) -> tuple[list[str], list[str]]:
    """Discard superseded MACHINE rows; keep the ones a person corrected.

    The shape every "delete prior output, then save fresh" site needs. Those
    sites exist for a real reason — without them re-runs accumulate duplicates
    — but an unconditional delete cannot tell last run's output from a
    correction, and destroys both. This keeps the sweep and adds the question.

    ``proposal_for(row)`` returns what the re-run would have written in that
    row's place; it is recorded on the preserved row so the disagreement is
    visible rather than resolved in silence. Returns
    ``(deleted_ids, preserved_ids)`` so the caller can log honestly about what
    it declined to do.
    """
    if not rows:
        return [], []

    audited_ids = audited_row_ids(db, {row.id for row in rows})
    deleted: list[str] = []
    preserved: list[str] = []

    for row in rows:
        if resolve_curation(row, audited_ids=audited_ids).is_protected:
            proposal = proposal_for(row) if proposal_for else None
            if record_conflict(row, proposal=proposal, reason=reason):
                db.save(row)
            preserved.append(row.id)
            continue
        try:
            db.delete(row)
            deleted.append(row.id)
        except Exception as exc:  # pragma: no cover - storage-level failure
            import logging

            logging.getLogger(__name__).warning(
                "curation_guard: could not delete superseded row %s: %s", row.id, exc
            )

    return deleted, preserved


def _next_metadata(row: Any) -> dict:
    """Copy the row's metadata so callers can compare before/after.

    A copy rather than in-place mutation: the caller decides whether anything
    changed, and so writes only when it did (that is what makes a re-run over
    settled rows a genuine no-op rather than a churn of identical saves).
    """
    metadata = getattr(row, marker_field(row), None)
    return dict(metadata) if isinstance(metadata, dict) else {}


def stamp(
    row: Any,
    *,
    source: CurationSource,
    actor: str | None = None,
    basis: str | None = None,
) -> bool:
    """Record who asserted this row. Returns True if the row changed.

    Stamping is what stops the audit-table derivation being repeated forever:
    a resolved verdict is written down once, with its basis, and is thereafter
    read straight off the row.
    """
    metadata = _next_metadata(row)
    existing = metadata.get(CURATION_KEY)
    marker = {
        "source": source.value,
        "actor": actor,
        "asserted_at": utc_now().isoformat(),
        "basis": basis or "stamped",
    }
    # Preserve an outstanding conflict and the readings already corrected
    # away from: stamping provenance is not the same act as resolving a
    # disagreement or un-rejecting a reading. Dropping either here would
    # silently discard the extractor's candidate, or let a second edit erase
    # the first edit's protection — a guard that decays after one use.
    if isinstance(existing, dict):
        for carried in (CONFLICT_KEY, SUPERSEDED_KEY):
            if carried in existing:
                marker[carried] = existing[carried]

    if isinstance(existing, dict):
        # `asserted_at` alone must not count as a change, or every run rewrites
        # every row and "already done" becomes unobservable.
        comparable_old = {k: v for k, v in existing.items() if k != "asserted_at"}
        comparable_new = {k: v for k, v in marker.items() if k != "asserted_at"}
        if comparable_old == comparable_new:
            return False
        marker["asserted_at"] = existing.get("asserted_at") or marker["asserted_at"]

    metadata[CURATION_KEY] = marker
    setattr(row, marker_field(row), metadata)
    return True


def record_conflict(row: Any, *, proposal: dict | None, reason: str) -> bool:
    """Record that a tool disagreed with a curated row. Returns True if changed.

    The tool's proposal is kept in full. Neither value is discarded: the user's
    stands as the row's value, the tool's is preserved beside it so the
    disagreement can be surfaced and decided rather than silently resolved in
    either direction.
    """
    metadata = _next_metadata(row)
    existing = metadata.get(CURATION_KEY)
    marker = dict(existing) if isinstance(existing, dict) else {"source": CurationSource.unknown.value}

    conflict = {"proposal": proposal, "reason": reason, "found_at": utc_now().isoformat()}

    prior = marker.get(CONFLICT_KEY)
    if isinstance(prior, dict) and prior.get("proposal") == proposal and prior.get("reason") == reason:
        # Same disagreement as last run — already recorded. Re-stamping the
        # timestamp would make an unchanged row look freshly touched.
        return False

    marker[CONFLICT_KEY] = conflict
    metadata[CURATION_KEY] = marker
    setattr(row, marker_field(row), metadata)
    return True


def clear_conflict(row: Any) -> bool:
    """Drop a recorded disagreement once it no longer holds. True if changed.

    Agreement clears a stale conflict — otherwise a disagreement the extractor
    has since abandoned would haunt the row forever.
    """
    metadata = _next_metadata(row)
    existing = metadata.get(CURATION_KEY)
    if not isinstance(existing, dict) or CONFLICT_KEY not in existing:
        return False

    marker = {k: v for k, v in existing.items() if k != CONFLICT_KEY}
    metadata[CURATION_KEY] = marker
    setattr(row, marker_field(row), metadata)
    return True


def record_superseded(row: Any, *, identity: dict) -> bool:
    """Remember the value a person corrected away from. True if changed.

    A stamp says "a person asserted this row"; it does not say *what they
    rejected*. Without that, a re-extraction that reproduces the pre-edit
    reading is unrecognisable — its text no longer matches the row it
    corrected, so ordinary dedup files it as a new claim and the archive ends
    up asserting both the correction and the thing corrected (#4499).

    The rejected readings accumulate on the row they govern, same as the
    stamp: a second correction adds a second entry, so a guard that worked
    once keeps working after the third re-run.
    """
    if not identity:
        return False

    metadata = _next_metadata(row)
    existing = metadata.get(CURATION_KEY)
    marker = dict(existing) if isinstance(existing, dict) else {"source": CurationSource.unknown.value}

    prior = marker.get(SUPERSEDED_KEY)
    history = [entry for entry in prior if isinstance(entry, dict)] if isinstance(prior, list) else []
    if any(entry == identity for entry in history):
        # Already recorded — re-recording would churn the row on every save.
        return False

    marker[SUPERSEDED_KEY] = [*history, identity]
    metadata[CURATION_KEY] = marker
    setattr(row, marker_field(row), metadata)
    return True


def superseded_identities(row: Any) -> list[dict]:
    """Readings a person has corrected away from on this row, oldest first."""
    metadata = getattr(row, marker_field(row), None)
    if not isinstance(metadata, dict):
        return []
    marker = metadata.get(CURATION_KEY)
    if not isinstance(marker, dict):
        return []
    entries = marker.get(SUPERSEDED_KEY)
    if not isinstance(entries, list):
        return []
    return [entry for entry in entries if isinstance(entry, dict)]


def has_conflict(row: Any) -> bool:
    metadata = getattr(row, marker_field(row), None)
    if not isinstance(metadata, dict):
        return False
    marker = metadata.get(CURATION_KEY)
    return isinstance(marker, dict) and CONFLICT_KEY in marker
