// Generated by fichero-server/scripts/export_openapi_schema.py. Do not edit.
//
// The contract this client was generated from (#5047). Baked at generation
// time, never computed at runtime: a parsed-then-reserialised document
// hashes differently, and the failure would be a universal refusal that
// looks exactly like a real mismatch.

public enum BakedContractIdentity {
    public static let version = "2026.9.29"
    public static let sha256 = "588ab3eb5630d5ea54d8d67e9640bb91c44350ee75c52063cd55a171a2896ceb"
}
