// Generated by fichero-server/scripts/export_openapi_schema.py. Do not edit.
//
// The contract this client was generated from (#5047). Baked at generation
// time, never computed at runtime: a parsed-then-reserialised document
// hashes differently, and the failure would be a universal refusal that
// looks exactly like a real mismatch.

public enum BakedContractIdentity {
    public static let version = "2026.9.29"
    public static let sha256 = "e831667f197e1e2af5b07ccd3df08dd1e5b148bfe7051e2756362f2a14d5ca4f"
}
