// Generated by fichero-server/scripts/export_openapi_schema.py. Do not edit.
//
// The contract this client was generated from (#5047). Baked at generation
// time, never computed at runtime: a parsed-then-reserialised document
// hashes differently, and the failure would be a universal refusal that
// looks exactly like a real mismatch.

public enum BakedContractIdentity {
    public static let version = "2026.9.29"
    public static let sha256 = "d10b6f950907b935660f55f3462de46cbafb44fe7565d3b607ff3888ecb049c4"
}
