//
//  ContractTests.swift
//  FicheroTests
//
//  Contract tests to ensure Swift and Python models stay in sync.
//  These tests load JSON fixtures generated by Python and verify
//  Swift can correctly parse them.
//
//  Tests are organized into:
//  1. Internal Swift model tests (WorkflowDefinition, WorkflowNode, etc.)
//  2. Generated API type tests (Components.Schemas.WorkflowDef, etc.)
//

@testable import Fichero
import FicheroAPIClient
import Foundation
import Testing

/// Path to the contract fixtures directory
private func contractsPath() -> URL {
    let fileManager = FileManager.default
    let starts = [
        URL(fileURLWithPath: #file).deletingLastPathComponent(),
        URL(fileURLWithPath: fileManager.currentDirectoryPath)
    ]

    for start in starts {
        var current = start
        while true {
            let candidate = current
                .appendingPathComponent("fichero-server")
                .appendingPathComponent("tests")
                .appendingPathComponent("contracts")
            if fileManager.fileExists(atPath: candidate.path) {
                return candidate
            }

            let parent = current.deletingLastPathComponent()
            if parent.path == current.path { break }
            current = parent
        }
    }

    return URL(fileURLWithPath: fileManager.currentDirectoryPath)
        .appendingPathComponent("fichero-server")
        .appendingPathComponent("tests")
        .appendingPathComponent("contracts")
}

private func fixturesPath() -> URL {
    contractsPath().appendingPathComponent("fixtures")
}

// MARK: - WorkflowDefinition Contract Tests

struct WorkflowDefinitionContractTests {

    @Test("Parse complete workflow fixture from Python")
    func parseCompleteWorkflow() throws {
        let fixturePath = fixturesPath().appendingPathComponent("workflow_complete.json")

        guard FileManager.default.fileExists(atPath: fixturePath.path) else {
            print("SKIP: Contract fixtures not generated (see #594). Run export_openapi_schema.py to enable.")
            return
        }

        let data = try Data(contentsOf: fixturePath)
        let decoder = JSONDecoder()

        let workflow = try decoder.decode(WorkflowDefinition.self, from: data)

        #expect(workflow.id == "test-workflow-abc123")
        #expect(workflow.name == "Test Workflow")
        #expect(workflow.description == "A workflow for testing serialization")
        #expect(workflow.provider == "openai")
        #expect(workflow.model == "gpt-4o")
        #expect(workflow.nodes.count == 2)
        #expect(workflow.edges.count == 1)
        #expect(workflow.folderPath == "/")
        #expect(workflow.sortOrder == 0)
    }

    @Test("Parse workflow with null values from Python")
    func parseWorkflowWithNulls() throws {
        let fixturePath = fixturesPath().appendingPathComponent("workflow_with_nulls.json")

        guard FileManager.default.fileExists(atPath: fixturePath.path) else {
            print("SKIP: Contract fixtures not generated (see #594). Run export_openapi_schema.py to enable.")
            return
        }

        let data = try Data(contentsOf: fixturePath)
        let decoder = JSONDecoder()

        let workflow = try decoder.decode(WorkflowDefinition.self, from: data)

        #expect(workflow.id == "test-workflow-nulls")
        #expect(workflow.name == "Workflow with Nulls")
        #expect(workflow.nodes.count == 1)

        // Verify null values are handled correctly
        let node = workflow.nodes[0]
        #expect(node.id == "node-null")
        #expect(node.tool == "echo")
        #expect(node.label == nil)  // null -> nil
        #expect(node.description == nil)  // null -> nil
        #expect(node.inputMappings.isEmpty)  // null -> []
        #expect(node.config == nil || node.config?.isEmpty == true)  // null -> nil or empty
    }

    @Test("Roundtrip serialization preserves data")
    func roundtripSerialization() throws {
        let fixturePath = fixturesPath().appendingPathComponent("workflow_complete.json")

        guard FileManager.default.fileExists(atPath: fixturePath.path) else {
            print("SKIP: Contract fixtures not generated (see #594). Run export_openapi_schema.py to enable.")
            return
        }

        let data = try Data(contentsOf: fixturePath)
        let decoder = JSONDecoder()
        let encoder = JSONEncoder()
        // Note: WorkflowDefinition uses CodingKeys for snake_case, don't use keyEncodingStrategy

        // Decode
        let original = try decoder.decode(WorkflowDefinition.self, from: data)

        // Encode
        let encoded = try encoder.encode(original)

        // Decode again (use fresh decoder without keyDecodingStrategy)
        let freshDecoder = JSONDecoder()
        let roundtripped = try freshDecoder.decode(WorkflowDefinition.self, from: encoded)

        // Core fields should match
        #expect(roundtripped.id == original.id)
        #expect(roundtripped.name == original.name)
        #expect(roundtripped.nodes.count == original.nodes.count)
        #expect(roundtripped.edges.count == original.edges.count)
    }
}

// MARK: - WorkflowNode Contract Tests

struct WorkflowNodeContractTests {

    @Test("Node with all fields populated")
    func nodeWithAllFields() throws {
        // JSON matching Python's NodeDef structure
        let json = """
        {
            "id": "node-123",
            "tool": "transcribe",
            "label": "Transcribe",
            "description": "Transcribes audio",
            "position_x": 100.0,
            "position_y": 200.0,
            "enabled": true,
            "input_ports": [
                {
                    "id": "input",
                    "name": "Input",
                    "port_type": "input",
                    "data_type": "files",
                    "required": true,
                    "description": ""
                }
            ],
            "output_ports": [],
            "input_mappings": [],
            "config": {"key": "value"}
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let node = try decoder.decode(WorkflowNode.self, from: json)

        #expect(node.id == "node-123")
        #expect(node.tool == "transcribe")
        #expect(node.label == "Transcribe")
        #expect(node.positionX == 100.0)
        #expect(node.positionY == 200.0)
        #expect(node.enabled == true)
        #expect(node.inputPorts.count == 1)
        #expect(node.inputPorts[0].dataType == "files")
    }

    @Test("Node with null optional fields")
    func nodeWithNullFields() throws {
        // JSON with null values as Swift might receive from Python
        let json = """
        {
            "id": "node-null",
            "tool": "echo",
            "label": null,
            "description": null,
            "position_x": 0.0,
            "position_y": 0.0,
            "enabled": true,
            "input_ports": null,
            "output_ports": null,
            "input_mappings": null,
            "config": null
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let node = try decoder.decode(WorkflowNode.self, from: json)

        // Null values should be converted to empty defaults
        #expect(node.label == nil)
        #expect(node.description == nil)
        #expect(node.inputPorts.isEmpty)  // null -> []
        #expect(node.outputPorts.isEmpty)  // null -> []
        #expect(node.inputMappings.isEmpty)  // null -> []
        #expect(node.config == nil)  // null -> nil (optional dict)
    }

    @Test("Node with integer position values")
    func nodeWithIntegerPositions() throws {
        // Swift might receive Int instead of Double from some JSON sources
        let json = """
        {
            "id": "node-int",
            "tool": "test",
            "position_x": 150,
            "position_y": 200,
            "enabled": true
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let node = try decoder.decode(WorkflowNode.self, from: json)

        #expect(node.positionX == 150.0)
        #expect(node.positionY == 200.0)
    }
}

// MARK: - WorkflowEdge Contract Tests

struct WorkflowEdgeContractTests {

    @Test("Edge with backend field names")
    func edgeWithBackendNames() throws {
        // Python sends source/target, not sourceNodeId/targetNodeId
        let json = """
        {
            "id": "edge-1",
            "source": "node-1",
            "target": "node-2",
            "source_port": "output",
            "target_port": "input",
            "condition": null,
            "label": null,
            "animated": false
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let edge = try decoder.decode(WorkflowEdge.self, from: json)

        #expect(edge.id == "edge-1")
        #expect(edge.sourceNodeId == "node-1")  // source -> sourceNodeId
        #expect(edge.targetNodeId == "node-2")  // target -> targetNodeId
        #expect(edge.sourcePortId == "output")
        #expect(edge.targetPortId == "input")
        #expect(edge.condition == nil)
        #expect(edge.animated == false)
    }

    @Test("Edge with condition")
    func edgeWithCondition() throws {
        let json = """
        {
            "id": "edge-conditional",
            "source": "node-switch",
            "target": "node-branch-a",
            "source_port": "output",
            "target_port": "input",
            "condition": "$.nodes.classify.result == \\"invoice\\"",
            "label": "Invoice Branch",
            "animated": true
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let edge = try decoder.decode(WorkflowEdge.self, from: json)

        #expect(edge.condition == "$.nodes.classify.result == \"invoice\"")
        #expect(edge.label == "Invoice Branch")
        #expect(edge.animated == true)
    }

    @Test("Edge encodes to backend format")
    func edgeEncodesToBackendFormat() throws {
        let edge = WorkflowEdge(
            id: "test-edge",
            sourceNodeId: "source-node",
            targetNodeId: "target-node",
            sourcePortId: "out",
            targetPortId: "in"
        )

        let encoder = JSONEncoder()
        let data = try encoder.encode(edge)
        let json = try JSONSerialization.jsonObject(with: data) as! [String: Any]

        // Should encode as source/target (backend format), not sourceNodeId/targetNodeId
        #expect(json["source"] as? String == "source-node")
        #expect(json["target"] as? String == "target-node")
        #expect(json["source_port"] as? String == "out")
        #expect(json["target_port"] as? String == "in")
    }
}

// MARK: - InputMapping Contract Tests

struct InputMappingContractTests {

    @Test("InputMapping with snake_case keys")
    func inputMappingSnakeCase() throws {
        let json = """
        {
            "port_id": "text",
            "source_path": "$.nodes.node-1.text",
            "transform": null
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let mapping = try decoder.decode(InputMapping.self, from: json)

        #expect(mapping.portId == "text")
        #expect(mapping.sourcePath == "$.nodes.node-1.text")
        #expect(mapping.transform == nil)
    }
}

// MARK: - PortInfo Contract Tests

struct PortInfoContractTests {

    @Test("All data types are accepted")
    func allDataTypes() throws {
        let dataTypes = ["any", "files", "file", "text", "json", "array", "image", "number", "boolean"]

        for dataType in dataTypes {
            let json = """
            {
                "id": "port-\(dataType)",
                "name": "Port \(dataType)",
                "port_type": "input",
                "data_type": "\(dataType)",
                "required": true,
                "description": "A \(dataType) port"
            }
            """.data(using: .utf8)!

            let decoder = JSONDecoder()
            let port = try decoder.decode(PortInfo.self, from: json)

            #expect(port.dataType == dataType)
        }
    }
}

// MARK: - Swift Encoding Compatibility Tests

struct SwiftEncodingCompatibilityTests {

    @Test("Swift encodes workflow in Python-compatible format")
    func swiftWorkflowEncodesForPython() throws {
        let workflow = WorkflowDefinition(
            id: "swift-test",
            name: "Swift Test Workflow",
            description: "Created in Swift",
            nodes: [
                WorkflowNode(
                    id: "node-1",
                    tool: "echo",
                    label: "Echo",
                    positionX: 100,
                    positionY: 200,
                    inputPorts: [],
                    outputPorts: [],
                    inputMappings: []
                )
            ],
            edges: []
        )

        let encoder = JSONEncoder()
        let data = try encoder.encode(workflow)
        let json = try JSONSerialization.jsonObject(with: data) as! [String: Any]

        // Verify snake_case keys for Python compatibility
        #expect(json["folder_path"] != nil)
        #expect(json["sort_order"] != nil)

        // Verify nodes array
        let nodes = json["nodes"] as! [[String: Any]]
        #expect(nodes.count == 1)
        #expect(nodes[0]["position_x"] != nil)
        #expect(nodes[0]["position_y"] != nil)
        #expect(nodes[0]["input_ports"] != nil)
        #expect(nodes[0]["output_ports"] != nil)
        #expect(nodes[0]["input_mappings"] != nil)
    }
}

// MARK: - Generated Types Contract Tests

/// Tests that verify the OpenAPI-generated types can parse Python fixtures.
/// These complement the internal Swift model tests above.
struct GeneratedTypesContractTests {

    @Test("Generated WorkflowDef preserves node payload")
    func workflowDefPreservesNodePayload() throws {
        // JSON matching Python workflow structure with embedded node payload
        let json = """
        {
            "id": "workflow-123",
            "name": "Workflow",
            "description": "Workflow with one node",
            "nodes": [
                {
                    "id": "node-123",
                    "tool": "transcribe",
                    "label": "Transcribe",
                    "description": "Transcribes audio",
                    "position_x": 100.0,
                    "position_y": 200.0,
                    "enabled": true,
                    "input_ports": [
                        {
                            "id": "input",
                            "name": "Input",
                            "port_type": "input",
                            "data_type": "files",
                            "required": true,
                            "description": ""
                        }
                    ],
                    "output_ports": []
                }
            ],
            "edges": [],
            "provider": null,
            "model": null
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let workflow = try decoder.decode(Components.Schemas.WorkflowDef.self, from: json)
        #expect(workflow.id == "workflow-123")
        #expect(workflow.name == "Workflow")
        #expect(workflow.nodes?.count == 1)
    }

    @Test("Generated EdgeDef parses backend format")
    func edgeDefParsesBackendFormat() throws {
        // Python sends source/target
        let json = """
        {
            "id": "edge-1",
            "source": "node-1",
            "target": "node-2",
            "source_port": "output",
            "target_port": "input"
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let edge = try decoder.decode(Components.Schemas.EdgeDef.self, from: json)

        #expect(edge.id == "edge-1")
        #expect(edge.source == "node-1")
        #expect(edge.target == "node-2")
        #expect(edge.sourcePort == "output")
        #expect(edge.targetPort == "input")
    }

    @Test("Generated PortDef parses all port types")
    func portDefParsesAllPortTypes() throws {
        let inputJson = """
        {
            "id": "port-1",
            "name": "Input",
            "port_type": "input",
            "data_type": "text",
            "required": true
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let inputPort = try decoder.decode(Components.Schemas.PortDef.self, from: inputJson)

        #expect(inputPort.id == "port-1")
        #expect(inputPort.portType == .input)
        #expect(inputPort.dataType == .text)
        #expect(inputPort.required == true)

        let outputJson = """
        {
            "id": "port-2",
            "name": "Output",
            "port_type": "output",
            "data_type": "image"
        }
        """.data(using: .utf8)!

        let outputPort = try decoder.decode(Components.Schemas.PortDef.self, from: outputJson)
        #expect(outputPort.portType == .output)
        #expect(outputPort.dataType == .image)
    }

    @Test("Generated WorkflowDef parses complete workflow")
    func workflowDefParsesComplete() throws {
        let json = """
        {
            "id": "test-workflow",
            "name": "Test Workflow",
            "description": "A test workflow",
            "nodes": [
                {
                    "id": "node-1",
                    "tool": "echo",
                    "position_x": 0,
                    "position_y": 0,
                    "input_ports": [],
                    "output_ports": [],
                    "enabled": true
                }
            ],
            "edges": [],
            "provider": "openai",
            "model": "gpt-4o"
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let workflow = try decoder.decode(Components.Schemas.WorkflowDef.self, from: json)

        #expect(workflow.id == "test-workflow")
        #expect(workflow.name == "Test Workflow")
        #expect(workflow.description == "A test workflow")
        #expect(workflow.nodes?.count == 1)
        #expect(workflow.edges?.isEmpty == true)
        #expect(workflow.provider == "openai")
        #expect(workflow.model == "gpt-4o")
    }

    @Test("Generated Document parses Python format")
    func documentParsesPythonFormat() throws {
        let json = """
        {
            "id": "doc-123",
            "name": "Test Document",
            "parent_id": null,
            "doc_type": "file",
            "file_type": "pdf",
            "path": "/documents/test.pdf",
            "status": "completed",
            "expected_thumbnail_path": "storage/thumbnails/do/doc-123.jpg",
            "expected_display_path": "storage/thumbnails/do/doc-123_display.jpg"
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let document = try decoder.decode(Components.Schemas.Document.self, from: json)

        #expect(document.id == "doc-123")
        #expect(document.name == "Test Document")
        #expect(document.parentId == nil)
        #expect(document.docType == .file)
        #expect(document.fileType == .pdf)
        #expect(document.status == .completed)
    }

    @Test("Generated workflow types handle null values")
    func generatedWorkflowTypesHandleNulls() throws {
        let json = """
        {
            "description": null,
            "id": "workflow-null",
            "name": "Workflow nulls",
            "nodes": [],
            "edges": [],
            "provider": null,
            "model": null
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let workflow = try decoder.decode(Components.Schemas.WorkflowDef.self, from: json)

        #expect(workflow.id == "workflow-null")
        #expect(workflow.description == nil)
        #expect(workflow.provider == nil)
        #expect(workflow.model == nil)
    }
}
