"""Reading a PAGE XML file SOMEBODY ELSE wrote (#4944).

**This is the first test of the format work, and deliberately not a round trip.**
A round trip of our own output proves our writer agrees with our reader — which two
consistently wrong halves also achieve. Reading a file produced by another tool is
what tests the claim Daniel's north star makes: that the model can take in what
eScriptorium and Transkribus speak.

The fixture below is hand-written in eScriptorium's shape (2013 namespace, integer
pixel `Coords`, `Baseline` on every line, a `ReadingOrder` of regions) rather than
generated by our own writer, for exactly that reason.
"""

from __future__ import annotations

import pytest

from fichero_server.formats import format_for, format_named, read_page
from fichero_server.formats.pagexml import PAGE_NS_2013

pytestmark = pytest.mark.source_model

#: An Arabic page: two regions, right-to-left, one line each, with baselines. The
#: 2013 namespace is what eScriptorium writes in places, and refusing it would fail
#: the one test that matters.
ESCRIPTORIUM_SHAPED = f"""<?xml version="1.0" encoding="UTF-8"?>
<PcGts xmlns="{PAGE_NS_2013}">
  <Metadata>
    <Creator>escriptorium</Creator>
    <Created>2026-09-26T10:00:00</Created>
  </Metadata>
  <Page imageFilename="folio_12r.jpg" imageWidth="1000" imageHeight="2000">
    <ReadingOrder>
      <OrderedGroup id="ro_1">
        <RegionRefIndexed index="0" regionRef="r1"/>
        <RegionRefIndexed index="1" regionRef="r2"/>
      </OrderedGroup>
    </ReadingOrder>
    <TextRegion id="r1" primaryLanguage="ar" script="Arab" readingDirection="right-to-left">
      <Coords points="100,200 900,200 900,400 100,400"/>
      <TextLine id="l1">
        <Coords points="100,200 900,200 900,300 100,300"/>
        <Baseline points="100,290 900,290"/>
        <TextEquiv index="0"><Unicode>بسم الله الرحمن الرحيم</Unicode></TextEquiv>
      </TextLine>
    </TextRegion>
    <TextRegion id="r2" primaryLanguage="ar" script="Arab" readingDirection="right-to-left">
      <Coords points="100,500 900,500 900,700 100,700"/>
      <TextLine id="l2">
        <Coords points="100,500 900,500 900,600 100,600"/>
        <Baseline points="100,590 900,590"/>
        <TextEquiv index="0"><Unicode>قرش 1847 عام</Unicode></TextEquiv>
      </TextLine>
    </TextRegion>
  </Page>
</PcGts>
""".encode()


class TestReadingAnotherToolsFile:
    def test_the_regions_and_lines_arrive_with_their_granularity(self):
        page = read_page("pagexml", ESCRIPTORIUM_SHAPED)

        kinds = [segment.kind for segment in page.segments]
        assert kinds.count("region") == 2
        assert kinds.count("line") == 2
        # And a line knows which region it is in, by the FILE's ids, not ours.
        lines = [s for s in page.segments if s.kind == "line"]
        assert {line.parent_ref for line in lines} == {"r1", "r2"}

    def test_coordinates_come_back_normalised_against_the_stated_page_size(self):
        page = read_page("pagexml", ESCRIPTORIUM_SHAPED)
        region = next(s for s in page.segments if s.ref == "r1")

        assert page.image_size == (1000, 2000)
        # 100/1000 and 200/2000 — normalised, which is what the model stores. A
        # reader that kept pixels would put another coordinate system in the model.
        assert region.polygon[0] == pytest.approx([0.1, 0.1])
        assert region.rect == pytest.approx([0.1, 0.1, 0.8, 0.1])

    def test_the_baseline_survives_because_kraken_is_built_around_it(self):
        page = read_page("pagexml", ESCRIPTORIUM_SHAPED)
        line = next(s for s in page.segments if s.ref == "l1")

        assert len(line.baseline) == 2
        for point, expected in zip(line.baseline, ([0.1, 0.145], [0.9, 0.145])):
            assert point == pytest.approx(expected)

    def test_language_script_and_direction_arrive_as_the_model_words_them(self):
        """Slice 9 is what "any language, any direction" means, and this is where it
        pays: PAGE XML's `right-to-left` is the model's `rtl`, and the script code is
        ISO 15924 in both."""
        page = read_page("pagexml", ESCRIPTORIUM_SHAPED)
        region = next(s for s in page.segments if s.ref == "r1")

        assert region.language == "ar"
        assert region.script == "Arab"
        assert region.direction == "rtl"

    def test_the_text_arrives_byte_for_byte_in_reading_order(self):
        """`source.dir.logical-order-stored`: nothing reorders a right-to-left
        string. A reader that "fixed" the order would destroy the original."""
        page = read_page("pagexml", ESCRIPTORIUM_SHAPED)
        line = next(s for s in page.segments if s.ref == "l1")

        assert line.readings == [("transcription", "بسم الله الرحمن الرحيم")]

    def test_the_reading_order_arrives_as_a_named_order(self):
        """Slice 10 is PAGE XML's `ReadingOrder`. Without named orders there is
        nowhere to put this, and the round trip could not be expressed."""
        page = read_page("pagexml", ESCRIPTORIUM_SHAPED)

        assert len(page.orders) == 1
        assert page.orders[0].refs == ["r1", "r2"]

    def test_the_producer_is_read_as_a_name_and_not_believed_to_be_an_actor(self):
        page = read_page("pagexml", ESCRIPTORIUM_SHAPED)

        assert page.producer == "escriptorium"


class TestRecognisingTheFormat:
    def test_the_format_is_recognised_by_its_bytes_not_its_extension(self):
        """PAGE XML, ALTO, hOCR and TEI are all `.xml`. A harness that trusted the
        extension would import an ALTO file as PAGE XML and report the emptiness as
        the file's fault."""
        spec = format_for("folio_12r.xml", ESCRIPTORIUM_SHAPED)

        assert spec is not None
        assert spec.name == "pagexml"

    def test_a_file_that_is_not_pagexml_is_not_claimed(self):
        alto_shaped = b'<?xml version="1.0"?><alto xmlns="http://www.loc.gov/standards/alto/ns-v4#"/>'

        assert format_named("pagexml").sniff(alto_shaped) is False

    def test_a_document_with_no_page_element_is_refused_with_a_reason(self):
        with pytest.raises(ValueError) as raised:
            read_page("pagexml", b'<?xml version="1.0"?><PcGts/>')
        assert "not a PAGE XML document" in str(raised.value)


class TestTheFileIsParsedSafely:
    def test_an_external_entity_is_not_resolved(self):
        """`source.format.schemas-on-disk` in its most important sense: an archival
        tool is pointed at files people did not write, and a document that fetches
        an entity is a document that can read a researcher's filesystem."""
        hostile = f"""<?xml version="1.0"?>
        <!DOCTYPE PcGts [<!ENTITY secret SYSTEM "file:///etc/passwd">]>
        <PcGts xmlns="{PAGE_NS_2013}">
          <Page imageFilename="x.png" imageWidth="10" imageHeight="10">
            <TextRegion id="r1"><TextEquiv><Unicode>&secret;</Unicode></TextEquiv></TextRegion>
          </Page>
        </PcGts>
        """.encode()

        try:
            page = read_page("pagexml", hostile)
        except Exception:
            return  # refusing the document outright is also correct
        for segment in page.segments:
            for _kind, text in segment.readings:
                assert "root:" not in text
