"""Generated by fichero-server/scripts/export_openapi_schema.py. Do not edit.

The identity of the OpenAPI contract this build speaks, baked in at
generation time so it cannot be skewed by hand (#5047). `CONTRACT_SHA256`
is over the exact bytes of the committed `openapi.json`, which every copy
of the contract shares byte-for-byte -- including the one the Swift client
is generated from, so both ends hash the same document.
"""

CONTRACT_VERSION = "2026.9.29"
CONTRACT_SHA256 = "e74d63db5b13cc64ee763ae4e0859eb2175cf3022465489a93f5a2a942765781"
