"""Generated by fichero-server/scripts/export_openapi_schema.py. Do not edit.

The identity of the OpenAPI contract this build speaks, baked in at
generation time so it cannot be skewed by hand (#5047). `CONTRACT_SHA256`
is over the exact bytes of the committed `openapi.json`, which every copy
of the contract shares byte-for-byte -- including the one the Swift client
is generated from, so both ends hash the same document.
"""

CONTRACT_VERSION = "2026.9.29"
CONTRACT_SHA256 = "9eefc645eb0b5e4ce52904dc0e83326ff48c295e9c9a799f4b43f7cd07db22af"
