"""Fichero command-line client.

A thin HTTP-only client for the Fichero backend. It drives the same FastAPI
endpoints the SwiftUI app uses, so the backend can be exercised live without
the app. Contains no backend logic — every operation is one or two HTTP calls.

All modules in this package are hand-written except
``openapi_surface_generated.py``, which is regenerated by
``fichero-engine/scripts/generate_openapi_cli.py`` and must not be edited by
hand. Hand-written commands remain in ``fichero.__main__`` until a command
split has a concrete ownership boundary.
"""

from fichero.cli.client import DEFAULT_BASE_URL, FicheroClient, FicheroError

__all__ = ["FicheroClient", "FicheroError", "DEFAULT_BASE_URL"]
