"""Fichero MCP server — the engine's OpenAPI contract as MCP tools.

Every tool comes from the contract (#5453): ``openapi_tools_generated.py`` holds one tool per
engine operation, generated by ``fichero-server/scripts/generate_openapi_mcp.py`` exactly as the
CLI is, and each makes one ``FicheroClient.request`` call. Adding a route adds its tool.

An agent picks **toolsets** (OpenAPI tags) at start with ``--toolsets``, so it sees the tools for
its job and not all of them. The default is the recipe golden path (``DEFAULT_TOOLSETS``);
``--toolsets all`` lists every tool.

One route, one tool. The few hand-written tools left here are kept only where they do something
a single route does not (each says what, and names its routes); ``OPERATOR_ALIASES`` keeps the
names an existing agent configuration calls, pointing at the generated tool for the same route.

Reads use the default client; mutations use the agent account when one exists
(``_mutating_client``), so the audit log names the agent. A refused call returns the engine's
status and detail as an MCP tool error, never an empty result.

Usage::

    python -m fichero_mcp.server [--api-url URL] [--library-path PATH] [--toolsets TAG,TAG|all]

The console entry point ``fichero-mcp = "fichero_mcp.server:main"`` is declared
in pyproject.toml. Configuration falls back to the environment
(``FICHERO_API_URL``, ``FICHERO_LIBRARY_PATH``, ``FICHERO_API_KEY``) — the same
variables the CLI honours.
"""

from __future__ import annotations

import argparse
import logging
from typing import Any, Iterable, Optional

from mcp.server.fastmcp import FastMCP

from fichero_cli import FicheroClient
from fichero_mcp import openapi_runtime
from fichero_mcp.openapi_tools_generated import TAGS, TOOLS

logger = logging.getLogger(__name__)

mcp = FastMCP("fichero")

# Populated by main() from CLI args; None means "discover from environment",
# which FicheroClient already does.
_CONFIG: dict[str, Optional[str]] = {"base_url": None, "library_path": None}

#: The recipe golden path: what an agent driving a recipe needs, and no more.
DEFAULT_TOOLSETS = ("recipes", "training", "segments", "documents", "activity", "local-models", "hpc")

#: Old hand-written tool names an existing agent configuration (the fichero-operator agent's tool
#: list) still calls, each pointing at the generated tool for the SAME route. Registered whatever
#: the toolsets, so that configuration keeps working; remove an entry once no configuration names
#: it. An entry whose name IS its generated tool's name keeps that tool listed when its tag is not.
OPERATOR_ALIASES: dict[str, tuple[str, str]] = {
    "fichero_activity": ("GET", "/api/activity/recent"),
    "fichero_artifact_get": ("GET", "/api/artifacts/{artifact_id}"),
    "fichero_artifacts": ("GET", "/api/artifacts/document/{doc_id}"),
    "fichero_create_note": ("POST", "/api/notes"),
    "fichero_docs_get": ("GET", "/api/documents/{doc_id}"),
    "fichero_document_inspector": ("GET", "/api/documents/{document_id}/inspector"),
    "fichero_document_kg": ("GET", "/api/documents/{document_id}/knowledge-graph"),
    "fichero_document_text": ("GET", "/api/segments/document/{document_id}/text"),
    "fichero_formats_list": ("GET", "/api/formats"),
    "fichero_get_note": ("GET", "/api/notes/{note_id}"),
    "fichero_hpc_clusters": ("GET", "/api/hpc/clusters"),
    "fichero_hpc_dry_run_submit": ("POST", "/api/hpc/clusters/{cluster_id}/dry-run-submit"),
    "fichero_hpc_test_cluster": ("POST", "/api/hpc/clusters/{cluster_id}/test"),
    "fichero_kg_claims": ("GET", "/api/claims"),
    "fichero_kg_entities": ("GET", "/api/entities"),
    "fichero_kg_neighborhood": ("GET", "/api/kg/graph/neighborhood/{entity_id}"),
    "fichero_kg_search": ("GET", "/api/kg/search"),
    "fichero_kraken_status": ("GET", "/api/local-models/kraken/status"),
    "fichero_list_libraries": ("GET", "/api/registry"),
    "fichero_list_notes": ("GET", "/api/notes"),
    "fichero_local_models": ("GET", "/api/local-models"),
    "fichero_local_runtimes": ("GET", "/api/providers/local-runtimes"),
    "fichero_models_catalog": ("GET", "/api/local-inference/catalog"),
    "fichero_page_export": ("GET", "/api/documents/{doc_id}/export/{format_name}"),
    "fichero_provider_catalog": ("GET", "/api/providers/catalog"),
    "fichero_providers": ("GET", "/api/providers"),
    "fichero_reading_order_entries": ("GET", "/api/reading-orders/{order_id}/entries"),
    "fichero_reading_orders": ("GET", "/api/reading-orders/document/{document_id}"),
    "fichero_reveal_location": ("POST", "/api/locations/resolve"),
    "fichero_runtime_status": ("GET", "/api/local-inference/runtime"),
    "fichero_search": ("POST", "/api/search"),
    "fichero_segment": ("GET", "/api/segments/{segment_id}"),
    "fichero_segment_readings": ("GET", "/api/segments/{segment_id}/readings"),
    "fichero_segment_reference": ("GET", "/api/segments/{segment_id}/reference"),
    "fichero_segment_versions": ("GET", "/api/segments/{segment_id}/versions"),
    "fichero_segments": ("GET", "/api/segments/document/{doc_id}"),
    "fichero_segments_in_scope": ("GET", "/api/segments"),
    "fichero_workflow_run": ("POST", "/api/workflow-execution/execute"),
    "fichero_workflow_status": ("GET", "/api/workflow-execution/threads/{thread_id}/status"),
}

#: Hand-written tools whose one route a generated tool also covers, and why each stays. Every
#: other hand-written tool composes several routes or none (`test_one_route_one_tool` pins it).
KEPT_SINGLE_ROUTE: dict[str, str] = {
    "fichero_use_library": "sets this session's library, which no route does; its GET is only a probe",
    "fichero_docs_list": "answers lean summaries; the route's full rows made a 92-file listing 186 KB",
    "fichero_workflow_list": "answers lean summaries; the route's node/edge dump made the listing 450 KB",
    "fichero_page_import": "uploads the file from the MCP host with the YOLO dataset file found beside it",
}


def _client() -> FicheroClient:
    """Build a client from the server config (env-discovered when unset).

    The tools below use this synchronous client directly on the event loop.
    That is sound because this server only runs over stdio (see ``main``),
    where MCP dispatches one request at a time — there is no concurrency to
    block. A non-stdio transport would need an async client instead.
    """
    return FicheroClient(
        base_url=_CONFIG["base_url"],
        library_path=_CONFIG["library_path"],
        client_name="fichero-mcp",
    )


def _agent_client() -> FicheroClient:
    """Build the dedicated agent-account client for audited MCP mutations.

    Fail closed BEFORE any connection: building a client may dial the engine (to read its
    certificate), so an agent with no stored session must be refused first. Otherwise the
    refusal depends on whether an engine happens to be listening.
    """
    from fichero_cli import client as client_module

    if not client_module._read_token(as_user="agent"):
        raise RuntimeError("No stored session for agent; run `fichero auth login agent`.")
    client = FicheroClient(
        base_url=_CONFIG["base_url"],
        library_path=_CONFIG["library_path"],
        as_user="agent",
        client_name="fichero-mcp",
    )
    if not client.token:
        client.close()
        raise RuntimeError("No stored session for agent; run `fichero auth login agent`.")
    return client


def _mutating_client() -> FicheroClient:
    """Client for MUTATING tools: the agent account when one exists (#4469).

    With a stored agent session (`fichero auth login agent`, multiuser), the
    mutation is the agent's — actor "agent" in the audit. Without one
    (single-user engines have no accounts), the owner credential acts, and the
    X-Fichero-Client tag both clients send keeps the audit row truthful about
    WHICH surface used it: actor=owner, client=fichero-mcp — recorded, not
    silent.
    """
    try:
        return _agent_client()
    except RuntimeError:
        return _client()


# Late-bound, so a test that patches `_client` / `_mutating_client` patches the generated tools too.
openapi_runtime.configure(lambda: _client(), lambda: _mutating_client())

_BY_ROUTE = {(tool.method, tool.path): tool for tool in TOOLS}
_SELECTED: list[str] = []


def parse_toolsets(value: str | Iterable[str]) -> tuple[str, ...]:
    """Tags from ``--toolsets`` (a comma list, or ``all``); an unknown tag is an error naming the known."""
    names = [v.strip() for v in (value.split(",") if isinstance(value, str) else value) if v.strip()]
    if names == ["all"]:
        return TAGS
    unknown = sorted(set(names) - set(TAGS))
    if unknown:
        raise ValueError(f"unknown toolsets {unknown}; known: {', '.join(TAGS)} (or all)")
    return tuple(names)


def select_toolsets(toolsets: Iterable[str], server: FastMCP | None = None) -> list[str]:
    """Register the generated tools of ``toolsets`` (and the operator aliases) on ``server``.

    Replaces whatever an earlier call registered, so ``main`` can narrow or widen the default.
    Returns the names registered.
    """
    server = server or mcp
    if server is mcp:
        for name in _SELECTED:
            server.remove_tool(name)
        _SELECTED.clear()
    chosen = set(toolsets)
    names: list[str] = []
    for tool in TOOLS:
        if tool.tag in chosen:
            server.add_tool(tool.fn, name=tool.name)
            names.append(tool.name)
    hand_written = {t.name for t in server._tool_manager.list_tools()}
    for alias, route in OPERATOR_ALIASES.items():
        if alias not in hand_written:
            target = _BY_ROUTE[route]
            server.add_tool(target.fn, name=alias, description=f"Alias of `{target.name}`.\n\n{target.fn.__doc__}")
            names.append(alias)
    if server is mcp:
        _SELECTED.extend(names)
    return names


# -- hand-written tools that a single route cannot be --------------------------
@mcp.tool()
def fichero_health() -> Any:
    """Check that the Fichero backend is reachable.

    Routes: GET /api/health (a probe the generated surfaces leave out).
    """
    with _client() as client:
        return client.health()


@mcp.tool()
def fichero_use_library(path: str) -> Any:
    """Scope this MCP session to one library by its .fichero path.

    Every subsequent library-scoped tool (docs, search, workflows, KG, …)
    uses it. Without this, tools answer 400 asking for a library — the
    server binds NO library by default (Daniel, 2026-08-27: one server,
    all libraries).

    Kept (#5453): it sets this session's library, which no route does.
    Routes: GET /api/documents (a one-row probe that proves the choice).
    """
    _CONFIG["library_path"] = path
    with _client() as client:
        # Prove the choice immediately instead of deferring the failure to
        # the next tool call.
        client.request("GET", "/api/documents", params={"limit": 1})
    return {"library_path": path, "status": "selected"}


@mcp.tool()
def fichero_docs_list(
    parent_id: Optional[str] = None,
    doc_type: Optional[str] = None,
    file_type: Optional[str] = None,
    status: Optional[str] = None,
    limit: Optional[int] = None,
    offset: int = 0,
) -> Any:
    """List documents in the library, optionally filtered.

    Returns lean summaries (id, name, kind, type, status, child_count) — a
    full document dump made a 92-file folder listing 186KB, which forced
    silly limits (Daniel, 2026-08-27: "why is 50 limit?"). Use
    ``fichero_docs_get`` for one document's full record.

    Kept (#5453): the lean shape (``KEPT_SINGLE_ROUTE``).
    Routes: GET /api/documents.
    """
    with _client() as client:
        result = client.list_documents(
            parent_id=parent_id,
            doc_type=doc_type,
            file_type=file_type,
            status=status,
            limit=limit,
            offset=offset,
        )
    docs = result.get("documents") if isinstance(result, dict) else result
    keep = (
        "id", "parent_id", "name", "node_kind", "doc_type", "file_type",
        "status", "sequence", "child_count", "date_original",
    )

    def slim(doc: Any) -> dict:
        record = doc if isinstance(doc, dict) else doc.model_dump()
        return {k: record.get(k) for k in keep if record.get(k) is not None}

    return [slim(d) for d in (docs or [])]


@mcp.tool()
def fichero_workflow_list() -> Any:
    """List available workflows.

    Each entry carries the engine's own run eligibility (#3804):
    ``direct_runnable`` false means it is an internal component that only runs
    inside a parent workflow — ``fichero_workflow_run`` will refuse it — and
    ``requires_vision`` true means the run needs a vision-capable model.
    Read these; do not infer them from the node list.

    Returns lean summaries (id, name, description, eligibility) — the full
    node/edge dump made the listing 450KB.

    Kept (#5453): the lean shape (``KEPT_SINGLE_ROUTE``).
    Routes: GET /api/workflows.
    """
    with _client() as client:
        result = client.list_workflows()
    items = result.get("workflows") if isinstance(result, dict) else result
    keep = (
        "id", "name", "description", "folder_path", "tags",
        "direct_runnable", "requires_vision", "is_system",
    )

    def slim(wf: Any) -> dict:
        record = wf if isinstance(wf, dict) else wf.model_dump()
        return {k: record.get(k) for k in keep if record.get(k) is not None}

    return [slim(w) for w in (items or [])]


@mcp.tool()
def fichero_page_import(
    doc_id: str,
    path: str,
    format: str | None = None,
    name: str | None = None,
) -> Any:
    """Import a PAGE XML, ALTO, hOCR, TEI or YOLO file as a NEW PASS on one page.

    The other direction of `fichero_page_export`. Not `fichero_documents_import_file`, which puts a
    new document in the library: this adds somebody else's transcription of a page that
    is already there.

    Returns the new `pass_id`, the format that was RECOGNISED (which may not be what the
    file's name claimed — a renamed eScriptorium export still reads as `pagexml`), the
    counts that landed (`segments`, `readings`, `order_entries`), the file's `checksum`,
    and `geometry_problems`: how many shapes the file could not express properly and the
    engine repaired. For a multi-page TEI file, `pages_in_file` and `pages_left_out` name the
    pages that did NOT become this pass. **Report the recognised format, any repairs and any
    pages left out to the person.** An
    import described as clean when forty boxes were repaired is a confident wrong answer.

    The import does NOT become the working pass. Somebody else's file arriving is not a
    decision about which reading of the page is authoritative, so nothing already on the
    page changes.

    Refusals carry the sentence that matters: the same bytes already on this document
    (nothing was written, and the sentence names the pass that holds them), a file nothing
    recognises (the sentence lists the formats this build reads), or shapes lying outside
    the page the file declares (the sentence names the segments that disagree). Pass the
    sentence on rather than reporting that the import failed.

    Args:
        doc_id: The page's document id.
        path: Path to the interchange file on the machine THIS MCP server runs on. Its
            bytes are uploaded (for YOLO, with the classes.txt or data.yaml found beside
            it), so the engine may be remote.
        format: Force a format instead of recognising one from the bytes.
        name: What to call the new pass.

    Kept (#5453): the YOLO dataset file found beside the labels (``KEPT_SINGLE_ROUTE``).
    Routes: POST /api/documents/{doc_id}/import.
    """
    with _mutating_client() as client:
        return client.import_page(doc_id, path, import_format=format, name=name)


select_toolsets(DEFAULT_TOOLSETS)


def main() -> None:
    """Console entry point — runs the MCP server over stdio."""
    parser = argparse.ArgumentParser(description="Fichero MCP server")
    parser.add_argument(
        "--api-url",
        help="Backend base URL (default: $FICHERO_API_URL or http://127.0.0.1:8765).",
    )
    parser.add_argument(
        "--library-path",
        help="Path to the .fichero library package (default: $FICHERO_LIBRARY_PATH).",
    )
    parser.add_argument(
        "--toolsets",
        default=",".join(DEFAULT_TOOLSETS),
        help=(
            "Comma-separated OpenAPI tags whose generated tools to list, or `all` "
            f"(default: {','.join(DEFAULT_TOOLSETS)})."
        ),
    )
    args = parser.parse_args()
    try:
        toolsets = parse_toolsets(args.toolsets)
    except ValueError as exc:
        parser.error(str(exc))
    logging.basicConfig(level=logging.INFO)
    if args.api_url:
        _CONFIG["base_url"] = args.api_url
    if args.library_path:
        _CONFIG["library_path"] = args.library_path
    if set(toolsets) != set(DEFAULT_TOOLSETS):
        select_toolsets(toolsets)
    # A missing token is not fatal — unauthenticated endpoints still work — but
    # every authenticated tool call will then fail with a 401. Flag it once at
    # startup; each authenticated call also still raises a clear FicheroError.
    with _client() as probe:
        if not probe.token:
            logger.warning(
                "No Fichero auth token found. Set FICHERO_API_KEY, or start the "
                "engine (it writes the key file). Authenticated tool calls will "
                "be rejected until a token is available."
            )
    mcp.run()


if __name__ == "__main__":
    main()
