#!/usr/bin/env python3
"""Generate feature-tier artifacts from features.yaml.

Outputs:
  - fichero/fichero/Models/FeatureTiers.generated.swift
  - fichero-server/src/fichero_server/api/feature_tiers_generated.py
  - docs/user/features.md
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import json
import pprint

from ruamel.yaml import YAML

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "features.yaml"
SWIFT_OUT = ROOT / "fichero" / "fichero" / "Models" / "FeatureTiers.generated.swift"
PYTHON_OUT = ROOT / "fichero-server" / "src" / "fichero_server" / "api" / "feature_tiers_generated.py"
DOCS_OUT = ROOT / "docs" / "user" / "features.md"
TIER_ORDER = {"dev": 1, "alpha": 2, "beta": 3, "release": 4}
@dataclass(frozen=True)
class Feature:
    key: str
    name: str
    tier: str
    swift_flag: str | None
    routes: tuple[str, ...]
    ux_group: str
    notes: str


def _yaml() -> YAML:
    yaml = YAML(typ="safe")
    yaml.allow_duplicate_keys = False
    return yaml


def _swift_literal(value: str | None) -> str:
    if value is None:
        return "nil"
    return json.dumps(value, ensure_ascii=True)


def _python_literal(value: object) -> str:
    return pprint.pformat(value, indent=2, sort_dicts=True, width=100)


def load_features(path: Path = SOURCE) -> list[Feature]:
    raw = _yaml().load(path.read_text())
    if not isinstance(raw, list):
        raise ValueError("features.yaml must contain a top-level list")

    features: list[Feature] = []
    seen_keys: set[str] = set()
    seen_routes: dict[str, str] = {}
    for item in raw:
        if not isinstance(item, dict):
            raise ValueError("Every features.yaml entry must be a mapping")
        feature = Feature(
            key=str(item["key"]),
            name=str(item["name"]),
            tier=str(item["tier"]),
            swift_flag=None if item.get("swift_flag") is None else str(item["swift_flag"]),
            routes=tuple(str(route) for route in item.get("routes", [])),
            ux_group=str(item["ux_group"]),
            notes=str(item["notes"]),
        )
        if feature.tier not in TIER_ORDER:
            raise ValueError(f"Unknown tier {feature.tier!r} for {feature.key}")
        if feature.key in seen_keys:
            raise ValueError(f"Duplicate feature key {feature.key!r}")
        seen_keys.add(feature.key)
        for route in feature.routes:
            owner = seen_routes.get(route)
            if owner and owner != feature.key:
                raise ValueError(
                    f"Route prefix {route!r} is assigned to both {owner!r} and {feature.key!r}"
                )
            seen_routes[route] = feature.key
        features.append(feature)
    return features


def cumulative_route_sets(features: list[Feature]) -> dict[str, list[str]]:
    route_tiers = {route: feature.tier for feature in features for route in feature.routes}
    cumulative: dict[str, list[str]] = {}
    for active_tier, active_rank in TIER_ORDER.items():
        visible = sorted(
            route
            for route, route_tier in route_tiers.items()
            if TIER_ORDER[route_tier] >= active_rank
        )
        cumulative[active_tier] = visible
    return cumulative


def generate_swift(features: list[Feature]) -> str:
    lines = [
        "// Generated by scripts/gen_feature_tiers.py. Do not edit.",
        "// swiftlint:disable file_length",
        "import Foundation",
        "",
        "enum FeatureTier: Int, CaseIterable, Comparable {",
        "    case dev = 1",
        "    case alpha = 2",
        "    case beta = 3",
        "    case release = 4",
        "",
        "    static func < (lhs: FeatureTier, rhs: FeatureTier) -> Bool {",
        "        lhs.rawValue < rhs.rawValue",
        "    }",
        "}",
        "",
        "enum FeatureKey: String, CaseIterable {",
    ]
    lines.extend(f"    case {feature.key}" for feature in features)
    lines.extend(
        [
            "}",
            "",
            "struct FeatureDescriptor {",
            "    let name: String",
            "    let tier: FeatureTier",
            "    let swiftFlag: String?",
            "    let uxGroup: String",
            "    let notes: String",
            "}",
            "",
            " // swiftlint:disable:next type_body_length",
            "enum FeatureTiers {",
            "    static let map: [FeatureKey: FeatureDescriptor] = [",
        ]
    )
    for index, feature in enumerate(features):
        is_last = index == len(features) - 1
        lines.extend(
            [
                f"        .{feature.key}: .init(",
                f"            name: {json.dumps(feature.name, ensure_ascii=True)},",
                f"            tier: .{feature.tier},",
                f"            swiftFlag: {_swift_literal(feature.swift_flag)},",
                f"            uxGroup: {json.dumps(feature.ux_group, ensure_ascii=True)},",
                f"            notes: {json.dumps(feature.notes, ensure_ascii=True)}",
                "        )" if is_last else "        ),",
            ]
        )
    lines.extend(
        [
            "    ]",
            "}",
            "// swiftlint:enable file_length",
            "",
        ]
    )
    return "\n".join(lines)


def generate_python(features: list[Feature]) -> str:
    feature_tiers = {feature.key: feature.tier for feature in features}
    feature_flags = {feature.key: feature.swift_flag for feature in features}
    feature_groups = {feature.key: feature.ux_group for feature in features}
    route_tiers = {route: feature.tier for feature in features for route in feature.routes}
    payload = cumulative_route_sets(features)
    return "\n".join(
        [
            '"""Generated by scripts/gen_feature_tiers.py. Do not edit."""',
            "",
            f"FEATURE_TIERS = {_python_literal(feature_tiers)}",
            "",
            f"FEATURE_SWIFT_FLAGS = {_python_literal(feature_flags)}",
            "",
            f"FEATURE_GROUPS = {_python_literal(feature_groups)}",
            "",
            f"ROUTE_PREFIX_TIERS = {_python_literal(route_tiers)}",
            "",
            f"CUMULATIVE_ROUTE_PREFIXES = {_python_literal(payload)}",
            "",
        ]
    )


def generate_docs(features: list[Feature]) -> str:
    lines = [
        "(AI generated. Not reviewed.)",
        "",
        "# Feature Matrix",
        "",
        "This page is generated from `features.yaml`.",
        "",
        "Build-tier visibility uses a maturity floor:",
        "",
        "- `release` builds show `release` features only.",
        "- `beta` builds show `beta` and `release` features.",
        "- `alpha` builds show `alpha`, `beta`, and `release` features.",
        "- `dev` builds show every tier.",
        "",
        "| Feature | Tier | UI flag | Backend route prefixes | Group | Notes |",
        "|---|---|---|---|---|---|",
    ]
    ordered = sorted(
        features,
        key=lambda feature: (-TIER_ORDER[feature.tier], feature.ux_group.lower(), feature.name.lower()),
    )
    for feature in ordered:
        swift_flag = f"`{feature.swift_flag}`" if feature.swift_flag else "-"
        routes = ", ".join(f"`{route}`" for route in feature.routes) if feature.routes else "-"
        lines.append(
            f"| {feature.name} | `{feature.tier}` | {swift_flag} | {routes} | "
            f"{feature.ux_group} | {feature.notes} |"
        )
    return "\n".join(lines) + "\n"


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text() == content:
        return
    path.write_text(content)


def main() -> int:
    features = load_features()
    write_if_changed(SWIFT_OUT, generate_swift(features))
    write_if_changed(PYTHON_OUT, generate_python(features))
    write_if_changed(DOCS_OUT, generate_docs(features))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
