#!/usr/bin/env python3
"""Generate the user-manual capability reference from the engine itself.

The manual has to say what every tool and every shipped workflow ACTUALLY does
— including the full prompt a step sends to a model — and it must never drift
from the app. So the reference is not written: it is generated, from the two
places the app itself reads.

  * tools     — ``fichero_server.workflows.registry.list_executable_tools()``
  * workflows — ``fichero_server/resources/default_workflows/*.json``
  * taxonomy  — ``fichero_server/resources/workflow_folders.json``

Output (markdown, so it feeds BOTH the mkdocs site and the .docx manuscript
round-trip in scripts/sync_manuscript.py):

    docs/user/reference/index.md                  workflows grouped by folder
    docs/user/reference/tools/index.md            tools grouped by category
    docs/user/reference/tools/<tool>.md           one page per tool
    docs/user/reference/workflows/index.md        every shipped workflow
    docs/user/reference/workflows/<slug>.md       one page per workflow

Everything is sorted, so regenerating the tree diffs cleanly. The mkdocs `nav`
entries for these pages are generated too, written between marker comments in
mkdocs.yml, so a new tool cannot appear as an unlinked page.

Usage:
    scripts/generate_capability_reference.py             # write pages + nav
    scripts/generate_capability_reference.py --out DIR   # write pages elsewhere
    scripts/generate_capability_reference.py --print-nav # nav block to stdout
    scripts/generate_capability_reference.py --self-test
    scripts/generate_capability_reference.py --help

Guardrail: scripts/check_capability_reference_current.py fails when the
committed pages no longer match what this script produces.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import unicodedata
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
ENGINE_SRC = ROOT / "fichero-server" / "src"
RESOURCES = ENGINE_SRC / "fichero_server" / "resources"
PRESETS_DIR = RESOURCES / "default_workflows"
FOLDERS_JSON = RESOURCES / "workflow_folders.json"
OUT_DIR = ROOT / "docs" / "user" / "reference"
MKDOCS = ROOT / "mkdocs.yml"

GENERATOR = "scripts/generate_capability_reference.py"
BANNER = f"<!-- GENERATED by {GENERATOR} — do not edit by hand. -->"
# Docs program convention (AGENTS.md, "Manuscript model"): unreviewed prose
# carries the badge until Daniel has made the page his own.
BADGE = "> \U0001f916 *AI Drafted (Not reviewed)*"

NAV_BEGIN = "      # BEGIN generated capability reference nav — " + GENERATOR
NAV_END = "      # END generated capability reference nav"


# --------------------------------------------------------------------------
# small text helpers
# --------------------------------------------------------------------------


def slugify(text: str) -> str:
    """Stable file-name slug for a workflow name."""
    plain = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    plain = re.sub(r"[^a-zA-Z0-9]+", "-", plain).strip("-").lower()
    return plain[:60].strip("-") or "untitled"


def cell(value: Any) -> str:
    """One markdown table cell: single line, pipes escaped."""
    if value is None or value == "":
        return "—"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, (dict, list)):
        text = json.dumps(value, sort_keys=True)
    else:
        text = str(value)
    return re.sub(r"\s+", " ", text).replace("|", r"\|").strip() or "—"


def fenced(text: str, language: str = "text") -> list[str]:
    """Fence a block with enough backticks to survive backticks inside it."""
    longest = max((len(run) for run in re.findall(r"`+", text)), default=0)
    fence = "`" * max(3, longest + 1)
    return [f"{fence}{language}", text.rstrip("\n"), fence, ""]


def page_header(title: str) -> list[str]:
    return [BANNER, "", f"# {title}", "", BADGE, ""]


# --------------------------------------------------------------------------
# engine access
# --------------------------------------------------------------------------


def load_tools() -> list[Any]:
    """Every executable tool, sorted by name so output is deterministic."""
    if str(ENGINE_SRC) not in sys.path:
        sys.path.insert(0, str(ENGINE_SRC))
    from fichero_server.workflows.registry import list_executable_tools

    return sorted(list_executable_tools(), key=lambda t: t.name)


def load_presets() -> list[dict[str, Any]]:
    """Shipped workflow presets, sorted by file name."""
    presets = []
    for path in sorted(PRESETS_DIR.glob("*.json")):
        data = json.loads(path.read_text())
        data["_file"] = path.name
        presets.append(data)
    return presets


def load_folders() -> list[dict[str, Any]]:
    data = json.loads(FOLDERS_JSON.read_text())
    return sorted(data.get("folders", []), key=lambda f: (f.get("sort_order", 999), f["path"]))


def effective_config(tool: Any, node_config: dict[str, Any]) -> dict[str, Any]:
    """What the node really runs with: tool defaults under the node's overrides."""
    merged = dict(getattr(tool, "config_defaults", {}) or {})
    merged.update(node_config or {})
    return merged


def tool_prompt(tool: Any, config: dict[str, Any] | None = None) -> str | None:
    """The prompt this tool sends, resolved through its own prompt builder."""
    return tool.get_prompt(config if config is not None else dict(tool.config_defaults or {}))


# --------------------------------------------------------------------------
# tool pages
# --------------------------------------------------------------------------


def port_table(ports: list[Any], empty: str) -> list[str]:
    if not ports:
        return [empty, ""]
    lines = [
        "| Port | Type | Required | What it is |",
        "| --- | --- | --- | --- |",
    ]
    for port in ports:
        data_type = getattr(port.data_type, "value", port.data_type)
        required = cell(port.required) if port.port_type == "input" else "—"
        lines.append(
            f"| {cell(port.name)} (`{port.id}`) | `{cell(data_type)}` | "
            f"{required} | {cell(port.description)} |"
        )
    lines.append("")
    return lines


def option_table(tool: Any) -> list[str]:
    schema = tool.config_schema or {}
    if not schema:
        return ["This tool has no options.", ""]
    defaults = tool.config_defaults or {}
    lines = ["| Option | Type | Default | What it does |", "| --- | --- | --- | --- |"]
    for key in sorted(schema):
        spec = schema[key] if isinstance(schema[key], dict) else {}
        described = (spec.get("description") or "").strip()
        if described and described[-1] not in ".!?":
            described += "."
        if spec.get("enum"):
            described = f"{described} One of: {', '.join(str(v) for v in spec['enum'])}."
        if spec.get("x-hidden"):
            described = f"{described} (Not shown in the editor.)"
        default = defaults.get(key, spec.get("default"))
        lines.append(
            f"| `{key}` | {cell(spec.get('type', 'any'))} | {cell(default)} | {cell(described)} |"
        )
    lines.append("")
    return lines


def tool_page(tool: Any) -> str:
    lines = page_header(tool.display_name)
    if tool.description:
        lines += [tool.description.strip(), ""]

    lines += [
        "| | |",
        "| --- | --- |",
        f"| Tool id | `{tool.name}` |",
        f"| Category | {cell(tool.category)} |",
        f"| Uses a language model | {cell(tool.uses_llm)} |",
        f"| Needs a generative model | {cell(tool.requires_generative_model)} |",
        f"| Runs over many items | {cell(tool.supports_batch)} |",
        f"| Item handling | {cell(tool.parallelism)} |",
        f"| Structured output | {cell(tool.supports_structured_output)} |",
        f"| Verified end to end | {cell(tool.tested)} |",
        "",
        "## What it reads",
        "",
    ]
    lines += port_table(tool.input_ports, "This tool takes no inputs.")
    lines += ["## What it emits", ""]
    lines += port_table(tool.output_ports, "This tool emits nothing.")
    lines += ["## Options", ""]
    lines += option_table(tool)

    prompt = tool_prompt(tool)
    lines += ["## The prompt it sends", ""]
    if prompt:
        lines += [
            "This is what the tool asks a model, with every option left at its "
            "default. Changing the options above changes this text.",
            "",
        ]
        lines += fenced(prompt)
    else:
        lines += ["This tool does not send a prompt — it does its work in code.", ""]

    if tool.default_output_schema:
        lines += ["## The answer shape it expects", ""]
        lines += fenced(json.dumps(tool.default_output_schema, indent=2, sort_keys=True), "json")

    return "\n".join(lines).rstrip("\n") + "\n"


def tools_index_page(tools: list[Any]) -> str:
    lines = page_header("Every tool")
    lines += [
        "A tool is one step: it reads something, does one job, and emits a result. "
        "Workflows are tools wired together. Each page below says what the tool "
        f"reads and emits, every option it takes, and — for tools that ask a model "
        f"— the exact words it sends. There are {len(tools)} of them.",
        "",
    ]
    by_category: dict[str, list[Any]] = {}
    for tool in tools:
        by_category.setdefault(tool.category, []).append(tool)
    for category in sorted(by_category):
        lines += [f"## {category.title()}", "", "| Tool | What it does | Uses a model |", "| --- | --- | --- |"]
        for tool in sorted(by_category[category], key=lambda t: (t.display_name, t.name)):
            link = f"[{tool.display_name}](tools/{tool.name}.md)"
            lines.append(f"| {link} | {cell(tool.description)} | {cell(tool.uses_llm)} |")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


# --------------------------------------------------------------------------
# workflow pages
# --------------------------------------------------------------------------


def run_order(preset: dict[str, Any]) -> list[dict[str, Any]]:
    """Nodes in the order the run reaches them.

    A stable topological sort: ties break on the node's position in the file,
    so the same preset always renders the same way.
    """
    nodes = preset.get("nodes", []) or []
    index = {node["id"]: position for position, node in enumerate(nodes)}
    incoming = {node["id"]: 0 for node in nodes}
    outgoing: dict[str, list[str]] = {node["id"]: [] for node in nodes}
    for edge in preset.get("edges", []) or []:
        source, target = edge.get("source"), edge.get("target")
        if source in incoming and target in incoming:
            outgoing[source].append(target)
            incoming[target] += 1

    ready = sorted((n["id"] for n in nodes if incoming[n["id"]] == 0), key=lambda i: index[i])
    ordered: list[str] = []
    while ready:
        current = ready.pop(0)
        ordered.append(current)
        for target in sorted(outgoing[current], key=lambda i: index[i]):
            incoming[target] -= 1
            if incoming[target] == 0:
                ready.append(target)
        ready.sort(key=lambda i: index[i])

    # A cycle would drop nodes; show them rather than silently losing a step.
    ordered += sorted((n["id"] for n in nodes if n["id"] not in ordered), key=lambda i: index[i])
    by_id = {node["id"]: node for node in nodes}
    return [by_id[node_id] for node_id in ordered]


def workflow_page(preset: dict[str, Any], tools: dict[str, Any]) -> str:
    lines = page_header(preset["name"])
    if preset.get("description"):
        lines += [preset["description"].strip(), ""]
    lines += [
        "| | |",
        "| --- | --- |",
        f"| Folder | {cell(preset.get('folder_path'))} |",
        f"| Steps | {len(preset.get('nodes', []) or [])} |",
        f"| Tags | {cell(', '.join(preset.get('tags', []) or []))} |",
        "",
        "## Steps, in run order",
        "",
    ]

    for position, node in enumerate(run_order(preset), start=1):
        tool = tools.get(node.get("tool", ""))
        label = node.get("label") or (tool.display_name if tool else node.get("tool", "?"))
        lines += [f"### {position}. {label}", ""]
        if tool is None:
            lines += [
                f"Runs the `{node.get('tool')}` tool, which is not in the tool "
                "registry — this step cannot be described here.",
                "",
            ]
            continue

        lines += [
            f"Tool: [{tool.display_name}](../tools/{tool.name}.md) — "
            f"{tool.description or 'no description'}",
            "",
        ]

        node_config = node.get("config", {}) or {}
        if node_config:
            lines += ["Settings this step uses:", "", "| Option | Value |", "| --- | --- |"]
            for key in sorted(node_config):
                lines.append(f"| `{key}` | {cell(node_config[key])} |")
            lines.append("")

        config = effective_config(tool, node_config)
        prompt = tool_prompt(tool, config)
        if prompt:
            lines += ["What this step asks the model:", ""]
            lines += fenced(prompt)

    return "\n".join(lines).rstrip("\n") + "\n"


def workflows_index_page(presets: list[dict[str, Any]]) -> str:
    lines = page_header("Every workflow")
    lines += [
        "Fichero ships these workflows in every new library. You can run them as "
        "they are, or duplicate one and change its steps. Each page lists the "
        f"steps in run order with the prompt each one sends. There are "
        f"{len(presets)} of them.",
        "",
        "| Workflow | Folder | Steps | What it is for |",
        "| --- | --- | --- | --- |",
    ]
    for preset in sorted(presets, key=lambda p: p["name"]):
        link = f"[{preset['name']}](workflows/{slugify(preset['name'])}.md)"
        lines.append(
            f"| {link} | {cell(preset.get('folder_path'))} | "
            f"{len(preset.get('nodes', []) or [])} | {cell(preset.get('description'))} |"
        )
    lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def overview_page(presets: list[dict[str, Any]], tools: list[Any]) -> str:
    lines = page_header("Reference: workflows and tools")
    lines += [
        "This part of the manual is generated from the app itself, so it says what "
        "Fichero actually does rather than what someone remembered it doing. "
        f"It covers {len(presets)} shipped workflows and {len(tools)} tools.",
        "",
        "- [Every workflow](workflows/index.md) — the presets, step by step.",
        "- [Every tool](tools/index.md) — the single steps a workflow is built from.",
        "",
        "Workflows are grouped into folders that follow the route work takes: "
        "prepare the image, find the regions, read them, clean the reading, "
        "translate it, describe and extract, then catalogue, organise, export.",
        "",
    ]

    by_folder: dict[str, list[dict[str, Any]]] = {}
    for preset in presets:
        by_folder.setdefault(preset.get("folder_path") or "/", []).append(preset)

    known = [folder["path"] for folder in load_folders()]
    order = known + sorted(path for path in by_folder if path not in known)
    for path in order:
        entries = by_folder.get(path)
        if not entries:
            continue
        lines += [f"## {path.lstrip('/') or 'Uncategorised'}", ""]
        for preset in sorted(entries, key=lambda p: p["name"]):
            link = f"[{preset['name']}](workflows/{slugify(preset['name'])}.md)"
            lines.append(f"- {link} — {cell(preset.get('description'))}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


# --------------------------------------------------------------------------
# nav
# --------------------------------------------------------------------------


def nav_block(presets: list[dict[str, Any]], tools: list[Any]) -> str:
    """The mkdocs nav lines for the generated reference, marker to marker."""
    lines = [
        NAV_BEGIN,
        "      - Reference:",
        "          - Workflows & Tools: user/reference/index.md",
        "          - Workflows:",
        "              - Every Workflow: user/reference/workflows/index.md",
    ]
    for preset in sorted(presets, key=lambda p: p["name"]):
        page = f"user/reference/workflows/{slugify(preset['name'])}.md"
        lines.append(f"              - {preset['name']}: {page}")
    lines += [
        "          - Tools:",
        "              - Every Tool: user/reference/tools/index.md",
    ]
    for tool in sorted(tools, key=lambda t: (t.display_name, t.name)):
        lines.append(f"              - {tool.display_name}: user/reference/tools/{tool.name}.md")
    lines.append(NAV_END)
    return "\n".join(lines) + "\n"


def patch_mkdocs(block: str) -> bool:
    """Replace the marked nav region in mkdocs.yml. Returns True if it changed."""
    text = MKDOCS.read_text()
    if NAV_BEGIN not in text or NAV_END not in text:
        raise SystemExit(
            f"mkdocs.yml has no capability-reference nav markers.\n"
            f"  Add these two lines inside the User Guide nav section:\n"
            f"{NAV_BEGIN}\n{NAV_END}"
        )
    start = text.index(NAV_BEGIN)
    end = text.index(NAV_END) + len(NAV_END) + 1
    updated = text[:start] + block + text[end:]
    if updated == text:
        return False
    MKDOCS.write_text(updated)
    return True


def committed_nav_block() -> str:
    """What mkdocs.yml currently holds between the markers."""
    text = MKDOCS.read_text()
    if NAV_BEGIN not in text or NAV_END not in text:
        return ""
    start = text.index(NAV_BEGIN)
    end = text.index(NAV_END) + len(NAV_END) + 1
    return text[start:end]


# --------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------


def generate(out_dir: Path) -> dict[str, int]:
    """Write the whole reference tree. Returns counts of what was written."""
    tools = load_tools()
    presets = load_presets()
    by_name = {tool.name: tool for tool in tools}

    if out_dir.exists():
        shutil.rmtree(out_dir)
    (out_dir / "tools").mkdir(parents=True)
    (out_dir / "workflows").mkdir(parents=True)

    (out_dir / "index.md").write_text(overview_page(presets, tools))
    (out_dir / "tools" / "index.md").write_text(tools_index_page(tools))
    (out_dir / "workflows" / "index.md").write_text(workflows_index_page(presets))
    for tool in tools:
        (out_dir / "tools" / f"{tool.name}.md").write_text(tool_page(tool))
    for preset in presets:
        page = out_dir / "workflows" / f"{slugify(preset['name'])}.md"
        page.write_text(workflow_page(preset, by_name))

    return {"tools": len(tools), "workflows": len(presets)}


def self_test() -> int:
    assert slugify("Capture OCR + Transcribe") == "capture-ocr-transcribe"
    assert cell("a | b") == r"a \| b"
    assert cell(True) == "yes"
    assert cell(None) == "—"
    assert fenced("has ``` inside")[0] == "````text"
    preset = {
        "nodes": [{"id": "c"}, {"id": "a"}, {"id": "b"}],
        "edges": [
            {"source": "a", "target": "b"},
            {"source": "b", "target": "c"},
        ],
    }
    assert [n["id"] for n in run_order(preset)] == ["a", "b", "c"]
    cyclic = {"nodes": [{"id": "x"}, {"id": "y"}], "edges": [
        {"source": "x", "target": "y"},
        {"source": "y", "target": "x"},
    ]}
    assert len(run_order(cyclic)) == 2, "a cycle must not drop steps"
    print("generate_capability_reference self-test passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", type=Path, default=None, help="write pages here instead of docs/user/reference")
    parser.add_argument("--print-nav", action="store_true", help="print the mkdocs nav block and exit")
    parser.add_argument("--self-test", action="store_true", help="run the built-in checks")
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    if args.print_nav:
        sys.stdout.write(nav_block(load_presets(), load_tools()))
        return 0

    out_dir = args.out or OUT_DIR
    counts = generate(out_dir)
    print(f"wrote {counts['tools']} tool pages and {counts['workflows']} workflow pages")
    print(f"  into {out_dir}")

    if args.out is None:
        changed = patch_mkdocs(nav_block(load_presets(), load_tools()))
        print("  mkdocs.yml nav " + ("updated" if changed else "already current"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
