#!/usr/bin/env bash
# release-notes-gen.sh — build CHANGELOG.md by day from git history via a LOCAL ollama model.
# Zero Claude cost: all prose is generated by `ollama run` (cloud models on Daniel's ollama acct).
#
# Walks BACKWARD from the day before the lead entry to the SwiftUI/Python pivot, in 5-day chunks
# ("do 5 days, then start over"). For each day: gathers that day's commits + closed GitHub issues,
# asks the model for one Apple-style **New/Improved/Fixed** section (or SKIP if nothing user-facing),
# and appends `## YYYY-MM-DD` to CHANGELOG.md. Resumable via .release-notes-cursor.
#
# NOTE: this only ever walks BACKWARD toward the pivot — it backfills history, it
# does not add today. Curated per-release prose goes in RELEASE_NOTES.md, by hand.
#
# Usage:  bash scripts/release-notes-gen.sh            # run to completion in 5-day chunks
#         OLLAMA_MODEL=glm-5.1:cloud bash scripts/release-notes-gen.sh
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Use a NON-reasoning model — reasoning models (deepseek-v4-pro, etc.) flood stdout with
# chain-of-thought that the markers can't reliably fence. kimi/qwen3.5/gemma4 are clean.
MODEL="${OLLAMA_MODEL:-kimi-k2.7-code:cloud}"
NOTES="CHANGELOG.md"
CURSOR_FILE=".release-notes-cursor"
PIVOT="2025-12-05"     # SwiftUI/Python transition (GLAM, Dec 3-5 2025); stop here — no pre-pivot notes
CHUNK=5

prev_day() { date -v-1d -j -f "%Y-%m-%d" "$1" +%Y-%m-%d; }

# Default to the pivot, NOT a hardcoded mid-history date: the cursor file is
# gitignored, so on a fresh clone a stale default would re-append months of
# already-present entries. Backfill is complete; absent cursor ⇒ nothing to do.
# ponytail: to re-backfill a range, write its start date into .release-notes-cursor.
cursor="$(cat "$CURSOR_FILE" 2>/dev/null || echo "$PIVOT")"
echo "release-notes-gen: model=$MODEL start-cursor=$cursor pivot=$PIVOT"

while :; do
  for ((i=0; i<CHUNK; i++)); do
    cursor="$(prev_day "$cursor")"
    if [[ "$cursor" < "$PIVOT" ]]; then
      echo "Reached pivot $PIVOT — release notes complete."
      echo "$cursor" > "$CURSOR_FILE"; exit 0
    fi
    commits="$(git log --since="$cursor 00:00" --until="$cursor 23:59" --format='- %s' 2>/dev/null)"
    issues="$(gh issue list -R dtubb/fichero --state closed --search "closed:$cursor" --limit 100 \
                --json number,title --jq '.[] | "- #\(.number) \(.title)"' 2>/dev/null)"
    echo "$cursor" > "$CURSOR_FILE"
    if [[ -z "$commits" && -z "$issues" ]]; then echo "$cursor: no activity, skip"; continue; fi

    prompt="You write ONE day's entry as polished macOS 'What's New' release notes — the concise, benefit-led voice Apple uses in Mac App Store app updates (NOT a developer changelog, NOT raw dev notes, NOT a commit list). Lead each item with a bold heading: **New — <short title>.** / **Improved — <short title>.** / **Fixed — <short title>.** then 1–2 crisp end-user sentences in plain language. Fichero is a macOS document-management app (SwiftUI) with a Python FastAPI/LangGraph engine for archival OCR/transcription + a knowledge graph. Date: $cursor.

Below are that day's git commits and closed GitHub issues. Write a SHORT entry grouped under **New** / **Improved** / **Fixed** (omit any empty group). User-facing voice — summarize the meaningful changes, do NOT transcribe every commit. If the day is purely internal (refactors, tests, CI, deps, docs) with nothing a user would notice, write SKIP. Never invent features. Wrap your answer EXACTLY between a line ===NOTES_START=== and a line ===NOTES_END=== — put ONLY the entry body (or the word SKIP) between those markers, and nothing else outside them.

COMMITS:
${commits:-（none）}

CLOSED ISSUES:
${issues:-（none）}"

    raw="$(printf '%s' "$prompt" | ollama run "$MODEL" 2>/dev/null | LC_ALL=C sed $'s/\x1b\\[[0-9;?]*[a-zA-Z]//g; s/\x08//g')"
    # Extract ONLY between the sentinel markers (strips reasoning-model "thinking").
    out="$(printf '%s' "$raw" | awk '/===NOTES_START===/{f=1;next} /===NOTES_END===/{f=0;next} f' | awk 'NF||p{print; p=1}')"
    if [[ -z "$out" ]]; then echo "$cursor: no markers in output, skip"; continue; fi
    if [[ "$out" == *SKIP* ]] && [[ ${#out} -lt 40 ]]; then echo "$cursor: SKIP (internal-only)"; continue; fi
    printf '\n## %s\n\n%s\n\n---\n' "$cursor" "$out" >> "$NOTES"
    echo "$cursor: appended"
  done
  sleep 2
done
