#!/usr/bin/env bash
# release-notes-gen.sh — build RELEASE_NOTES.md by day from git history via a LOCAL ollama model.
# Zero Claude cost: all prose is generated by `ollama run` (cloud models on Daniel's ollama acct).
#
# Walks BACKWARD from the day before the lead entry to the SwiftUI/Python pivot, in 5-day chunks
# ("do 5 days, then start over"). For each day: gathers that day's commits + closed GitHub issues,
# asks the model for one Apple-style **New/Improved/Fixed** section (or SKIP if nothing user-facing),
# and appends `## YYYY-MM-DD` to RELEASE_NOTES.md. Resumable via .release-notes-cursor.
#
# Usage:  bash scripts/release-notes-gen.sh            # run to completion in 5-day chunks
#         OLLAMA_MODEL=glm-5.1:cloud bash scripts/release-notes-gen.sh
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

MODEL="${OLLAMA_MODEL:-deepseek-v4-pro:cloud}"
NOTES="RELEASE_NOTES.md"
CURSOR_FILE=".release-notes-cursor"
PIVOT="2025-11-01"     # SwiftUI/Python migration ~here; stop at it
CHUNK=5

prev_day() { date -v-1d -j -f "%Y-%m-%d" "$1" +%Y-%m-%d; }

cursor="$(cat "$CURSOR_FILE" 2>/dev/null || echo 2026-06-23)"
echo "release-notes-gen: model=$MODEL start-cursor=$cursor pivot=$PIVOT"

while :; do
  for ((i=0; i<CHUNK; i++)); do
    cursor="$(prev_day "$cursor")"
    if [[ "$cursor" < "$PIVOT" ]]; then
      echo "Reached pivot $PIVOT — release notes complete."
      echo "$cursor" > "$CURSOR_FILE"; exit 0
    fi
    commits="$(git log --since="$cursor 00:00" --until="$cursor 23:59" --format='- %s' 2>/dev/null)"
    issues="$(gh issue list -R dtubb/fichero --state closed --search "closed:$cursor" --limit 100 \
                --json number,title --jq '.[] | "- #\(.number) \(.title)"' 2>/dev/null)"
    echo "$cursor" > "$CURSOR_FILE"
    if [[ -z "$commits" && -z "$issues" ]]; then echo "$cursor: no activity, skip"; continue; fi

    prompt="You write ONE day's entry for Fichero's release notes, Apple 'what's new' style. Fichero is a macOS document-management app (SwiftUI) with a Python FastAPI/LangGraph engine for archival OCR/transcription + a knowledge graph. Date: $cursor.

Below are that day's git commits and closed GitHub issues. Write a SHORT entry grouped under **New** / **Improved** / **Fixed** (omit any empty group). User-facing voice — summarize the meaningful changes, do NOT transcribe every commit. If the day is purely internal (refactors, tests, CI, deps, docs) with nothing a user would notice, output exactly: SKIP. Never invent features. Output ONLY the entry body — no date header, no preamble.

COMMITS:
${commits:-（none）}

CLOSED ISSUES:
${issues:-（none）}"

    out="$(printf '%s' "$prompt" | ollama run "$MODEL" 2>/dev/null)"
    out="$(printf '%s' "$out" | awk 'NF||p{print; p=1}')"   # drop leading blank lines
    if [[ -z "$out" ]] || { [[ "$out" == *SKIP* ]] && [[ ${#out} -lt 40 ]]; }; then
      echo "$cursor: SKIP (internal-only)"; continue
    fi
    printf '\n## %s\n\n%s\n\n---\n' "$cursor" "$out" >> "$NOTES"
    echo "$cursor: appended"
  done
  sleep 2
done
