//
//  ContractTests.swift
//  FicheroTests
//
//  Contract tests to ensure Swift and Python models stay in sync.
//  These tests load JSON fixtures generated by Python and verify
//  Swift can correctly parse them.
//

import Foundation
import Testing
@testable import Fichero

/// Path to the contract fixtures directory
/// Navigate from FicheroTests to the shared contracts folder
private func contractsPath() -> URL {
    // From: Fichero/FicheroTests/ContractTests.swift
    // To: tests/contracts/fixtures/
    let thisFile = URL(fileURLWithPath: #file)
    return thisFile
        .deletingLastPathComponent()  // FicheroTests
        .deletingLastPathComponent()  // Fichero
        .deletingLastPathComponent()  // Fichero (project folder)
        .appendingPathComponent("tests")
        .appendingPathComponent("contracts")
}

private func fixturesPath() -> URL {
    contractsPath().appendingPathComponent("fixtures")
}

// MARK: - WorkflowDefinition Contract Tests

struct WorkflowDefinitionContractTests {

    @Test("Parse complete workflow fixture from Python")
    func parseCompleteWorkflow() throws {
        let fixturePath = fixturesPath().appendingPathComponent("workflow_complete.json")

        guard FileManager.default.fileExists(atPath: fixturePath.path) else {
            Issue.record("Contract fixtures not generated. Run: python scripts/export_api_schemas.py")
            return
        }

        let data = try Data(contentsOf: fixturePath)
        let decoder = JSONDecoder()

        let workflow = try decoder.decode(WorkflowDefinition.self, from: data)

        #expect(workflow.id == "test-workflow-abc123")
        #expect(workflow.name == "Test Workflow")
        #expect(workflow.description == "A workflow for testing serialization")
        #expect(workflow.provider == "openai")
        #expect(workflow.model == "gpt-4o")
        #expect(workflow.nodes.count == 2)
        #expect(workflow.edges.count == 1)
        #expect(workflow.folderPath == "/")
        #expect(workflow.sortOrder == 0)
    }

    @Test("Parse workflow with null values from Python")
    func parseWorkflowWithNulls() throws {
        let fixturePath = fixturesPath().appendingPathComponent("workflow_with_nulls.json")

        guard FileManager.default.fileExists(atPath: fixturePath.path) else {
            Issue.record("Contract fixtures not generated. Run: python scripts/export_api_schemas.py")
            return
        }

        let data = try Data(contentsOf: fixturePath)
        let decoder = JSONDecoder()

        let workflow = try decoder.decode(WorkflowDefinition.self, from: data)

        #expect(workflow.id == "test-workflow-nulls")
        #expect(workflow.name == "Workflow with Nulls")
        #expect(workflow.nodes.count == 1)

        // Verify null values are handled correctly
        let node = workflow.nodes[0]
        #expect(node.id == "node-null")
        #expect(node.tool == "echo")
        #expect(node.label == nil)  // null -> nil
        #expect(node.description == nil)  // null -> nil
        #expect(node.inputMappings.isEmpty)  // null -> []
        #expect(node.config == nil || node.config?.isEmpty == true)  // null -> nil or empty
    }

    @Test("Roundtrip serialization preserves data")
    func roundtripSerialization() throws {
        let fixturePath = fixturesPath().appendingPathComponent("workflow_complete.json")

        guard FileManager.default.fileExists(atPath: fixturePath.path) else {
            Issue.record("Contract fixtures not generated. Run: python scripts/export_api_schemas.py")
            return
        }

        let data = try Data(contentsOf: fixturePath)
        let decoder = JSONDecoder()
        let encoder = JSONEncoder()
        // Note: WorkflowDefinition uses CodingKeys for snake_case, don't use keyEncodingStrategy

        // Decode
        let original = try decoder.decode(WorkflowDefinition.self, from: data)

        // Encode
        let encoded = try encoder.encode(original)

        // Decode again (use fresh decoder without keyDecodingStrategy)
        let freshDecoder = JSONDecoder()
        let roundtripped = try freshDecoder.decode(WorkflowDefinition.self, from: encoded)

        // Core fields should match
        #expect(roundtripped.id == original.id)
        #expect(roundtripped.name == original.name)
        #expect(roundtripped.nodes.count == original.nodes.count)
        #expect(roundtripped.edges.count == original.edges.count)
    }
}

// MARK: - WorkflowNode Contract Tests

struct WorkflowNodeContractTests {

    @Test("Node with all fields populated")
    func nodeWithAllFields() throws {
        // JSON matching Python's NodeDef structure
        let json = """
        {
            "id": "node-123",
            "tool": "transcribe",
            "label": "Transcribe",
            "description": "Transcribes audio",
            "position_x": 100.0,
            "position_y": 200.0,
            "enabled": true,
            "input_ports": [
                {
                    "id": "input",
                    "name": "Input",
                    "port_type": "input",
                    "data_type": "files",
                    "required": true,
                    "description": ""
                }
            ],
            "output_ports": [],
            "input_mappings": [],
            "config": {"key": "value"}
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let node = try decoder.decode(WorkflowNode.self, from: json)

        #expect(node.id == "node-123")
        #expect(node.tool == "transcribe")
        #expect(node.label == "Transcribe")
        #expect(node.positionX == 100.0)
        #expect(node.positionY == 200.0)
        #expect(node.enabled == true)
        #expect(node.inputPorts.count == 1)
        #expect(node.inputPorts[0].dataType == "files")
    }

    @Test("Node with null optional fields")
    func nodeWithNullFields() throws {
        // JSON with null values as Swift might receive from Python
        let json = """
        {
            "id": "node-null",
            "tool": "echo",
            "label": null,
            "description": null,
            "position_x": 0.0,
            "position_y": 0.0,
            "enabled": true,
            "input_ports": null,
            "output_ports": null,
            "input_mappings": null,
            "config": null
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let node = try decoder.decode(WorkflowNode.self, from: json)

        // Null values should be converted to empty defaults
        #expect(node.label == nil)
        #expect(node.description == nil)
        #expect(node.inputPorts.isEmpty)  // null -> []
        #expect(node.outputPorts.isEmpty)  // null -> []
        #expect(node.inputMappings.isEmpty)  // null -> []
        #expect(node.config == nil)  // null -> nil (optional dict)
    }

    @Test("Node with integer position values")
    func nodeWithIntegerPositions() throws {
        // Swift might receive Int instead of Double from some JSON sources
        let json = """
        {
            "id": "node-int",
            "tool": "test",
            "position_x": 150,
            "position_y": 200,
            "enabled": true
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let node = try decoder.decode(WorkflowNode.self, from: json)

        #expect(node.positionX == 150.0)
        #expect(node.positionY == 200.0)
    }
}

// MARK: - WorkflowEdge Contract Tests

struct WorkflowEdgeContractTests {

    @Test("Edge with backend field names")
    func edgeWithBackendNames() throws {
        // Python sends source/target, not sourceNodeId/targetNodeId
        let json = """
        {
            "id": "edge-1",
            "source": "node-1",
            "target": "node-2",
            "source_port": "output",
            "target_port": "input",
            "condition": null,
            "label": null,
            "animated": false
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let edge = try decoder.decode(WorkflowEdge.self, from: json)

        #expect(edge.id == "edge-1")
        #expect(edge.sourceNodeId == "node-1")  // source -> sourceNodeId
        #expect(edge.targetNodeId == "node-2")  // target -> targetNodeId
        #expect(edge.sourcePortId == "output")
        #expect(edge.targetPortId == "input")
        #expect(edge.condition == nil)
        #expect(edge.animated == false)
    }

    @Test("Edge with condition")
    func edgeWithCondition() throws {
        let json = """
        {
            "id": "edge-conditional",
            "source": "node-switch",
            "target": "node-branch-a",
            "source_port": "output",
            "target_port": "input",
            "condition": "$.nodes.classify.result == \\"invoice\\"",
            "label": "Invoice Branch",
            "animated": true
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let edge = try decoder.decode(WorkflowEdge.self, from: json)

        #expect(edge.condition == "$.nodes.classify.result == \"invoice\"")
        #expect(edge.label == "Invoice Branch")
        #expect(edge.animated == true)
    }

    @Test("Edge encodes to backend format")
    func edgeEncodesToBackendFormat() throws {
        let edge = WorkflowEdge(
            id: "test-edge",
            sourceNodeId: "source-node",
            targetNodeId: "target-node",
            sourcePortId: "out",
            targetPortId: "in"
        )

        let encoder = JSONEncoder()
        let data = try encoder.encode(edge)
        let json = try JSONSerialization.jsonObject(with: data) as! [String: Any]

        // Should encode as source/target (backend format), not sourceNodeId/targetNodeId
        #expect(json["source"] as? String == "source-node")
        #expect(json["target"] as? String == "target-node")
        #expect(json["source_port"] as? String == "out")
        #expect(json["target_port"] as? String == "in")
    }
}

// MARK: - InputMapping Contract Tests

struct InputMappingContractTests {

    @Test("InputMapping with snake_case keys")
    func inputMappingSnakeCase() throws {
        let json = """
        {
            "port_id": "text",
            "source_path": "$.nodes.node-1.text",
            "transform": null
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        let mapping = try decoder.decode(InputMapping.self, from: json)

        #expect(mapping.portId == "text")
        #expect(mapping.sourcePath == "$.nodes.node-1.text")
        #expect(mapping.transform == nil)
    }
}

// MARK: - PortInfo Contract Tests

struct PortInfoContractTests {

    @Test("All data types are accepted")
    func allDataTypes() throws {
        let dataTypes = ["any", "files", "file", "text", "json", "array", "image", "number", "boolean"]

        for dataType in dataTypes {
            let json = """
            {
                "id": "port-\(dataType)",
                "name": "Port \(dataType)",
                "port_type": "input",
                "data_type": "\(dataType)",
                "required": true,
                "description": "A \(dataType) port"
            }
            """.data(using: .utf8)!

            let decoder = JSONDecoder()
            let port = try decoder.decode(PortInfo.self, from: json)

            #expect(port.dataType == dataType)
        }
    }
}

// MARK: - Swift Encoding Compatibility Tests

struct SwiftEncodingCompatibilityTests {

    @Test("Swift encodes workflow in Python-compatible format")
    func swiftWorkflowEncodesForPython() throws {
        let workflow = WorkflowDefinition(
            id: "swift-test",
            name: "Swift Test Workflow",
            description: "Created in Swift",
            nodes: [
                WorkflowNode(
                    id: "node-1",
                    tool: "echo",
                    label: "Echo",
                    positionX: 100,
                    positionY: 200,
                    inputPorts: [],
                    outputPorts: [],
                    inputMappings: []
                )
            ],
            edges: []
        )

        let encoder = JSONEncoder()
        let data = try encoder.encode(workflow)
        let json = try JSONSerialization.jsonObject(with: data) as! [String: Any]

        // Verify snake_case keys for Python compatibility
        #expect(json["folder_path"] != nil)
        #expect(json["sort_order"] != nil)

        // Verify nodes array
        let nodes = json["nodes"] as! [[String: Any]]
        #expect(nodes.count == 1)
        #expect(nodes[0]["position_x"] != nil)
        #expect(nodes[0]["position_y"] != nil)
        #expect(nodes[0]["input_ports"] != nil)
        #expect(nodes[0]["output_ports"] != nil)
        #expect(nodes[0]["input_mappings"] != nil)
    }
}
