// Generated by scripts/gen_feature_tiers.py. Do not edit.
// swiftlint:disable file_length
import Foundation

enum FeatureTier: Int, CaseIterable, Comparable {
    case dev = 1
    case alpha = 2
    case beta = 3
    case release = 4

    static func < (lhs: FeatureTier, rhs: FeatureTier) -> Bool {
        lhs.rawValue < rhs.rawValue
    }
}

enum FeatureKey: String, CaseIterable {
    case library
    case reader
    case ingest
    case libraryAdvancedViews
    case libraryIconZoomControls
    case search
    case searchAdvancedViews
    case workflows
    case workflowEditorAdvancedViews
    case workflowChains
    case workflowImportExport
    case workflowRunOnSelection
    case workflowLangGraphPreview
    case batches
    case workflowToolsFiles
    case knowledgeGraph
    case curation
    case providers
    case modelComparison
    case cli
    case mcpServer
    case activity
    case research
    case settingsGeneralTab
    case settingsEngineTab
    case settingsShareTab
    case settingsUsersTab
    case settingsCaptureTab
    case chat
    case workflowToolsSearch
    case workflowToolsTransform
    case workflowToolsConvert
    case workflowToolsLogic
    case workflowToolsOutputs
    case workflowToolsAudio
    case workflowToolsVideo
    case workflowToolsMcp
    case workflowToolsAgents
    case providersExtended
    case settingsBackendTab
    case settingsModelsTab
    case libraryFilterToolbar
    case librarySearchSplitLayouts
    case claimHighlightSync
    case pdfScrollGridSync
    case workspaceMode
    case spatialMode
    case canvasRealityKit2D
    case canvasRealityKit3D
    case automation
    case mcpUi
    case agents
    case integrations
    case iiif
}

struct FeatureDescriptor {
    let name: String
    let tier: FeatureTier
    let swiftFlag: String?
    let uxGroup: String
    let notes: String
}

 // swiftlint:disable:next type_body_length
enum FeatureTiers {
    static let map: [FeatureKey: FeatureDescriptor] = [
        .library: .init(
            name: "Library",
            tier: .release,
            swiftFlag: nil,
            uxGroup: "Core",
            notes: "Import, organize, and browse a hierarchy of documents."
        ),
        .reader: .init(
            name: "Reader",
            tier: .release,
            swiftFlag: nil,
            uxGroup: "Core",
            notes: "PDFs, page images, extracted text, artifacts, and inspector."
        ),
        .ingest: .init(
            name: "Ingest",
            tier: .release,
            swiftFlag: nil,
            uxGroup: "Core",
            notes: "File and URL import into the library."
        ),
        .libraryAdvancedViews: .init(
            name: "Library advanced views",
            tier: .beta,
            swiftFlag: "fichero.features.library_advanced_views",
            uxGroup: "Core",
            notes: "Grid, list, table, and map views in the library."
        ),
        .libraryIconZoomControls: .init(
            name: "Library icon zoom controls",
            tier: .dev,
            swiftFlag: "fichero.features.library_icon_zoom_controls",
            uxGroup: "Core",
            notes: "Zoom controls for icon-based library layouts."
        ),
        .search: .init(
            name: "Search",
            tier: .release,
            swiftFlag: "fichero.features.search",
            uxGroup: "Core",
            notes: "Keyword and semantic search across the library."
        ),
        .searchAdvancedViews: .init(
            name: "Search advanced views",
            tier: .beta,
            swiftFlag: "fichero.features.search_advanced_views",
            uxGroup: "Core",
            notes: "Search results in all supported presentation modes."
        ),
        .workflows: .init(
            name: "Workflows",
            tier: .beta,
            swiftFlag: "fichero.features.workflows",
            uxGroup: "Processing",
            notes: "Visual workflow editor and execution surface."
        ),
        .workflowEditorAdvancedViews: .init(
            name: "Workflow editor advanced views",
            tier: .dev,
            swiftFlag: "fichero.features.workflow_editor_advanced_views",
            uxGroup: "Processing",
            notes: "Extra presentation modes in the workflow editor."
        ),
        .workflowChains: .init(
            name: "Workflow chains",
            tier: .beta,
            swiftFlag: "fichero.features.workflow_chains",
            uxGroup: "Processing",
            notes: "Multi-step composed workflow pipelines."
        ),
        .workflowImportExport: .init(
            name: "Workflow import and export",
            tier: .dev,
            swiftFlag: "fichero.features.workflow_import_export",
            uxGroup: "Processing",
            notes: "Import and export workflow definitions."
        ),
        .workflowRunOnSelection: .init(
            name: "Workflow run on selection",
            tier: .dev,
            swiftFlag: "fichero.features.workflow_run_on_selection",
            uxGroup: "Processing",
            notes: "Run the active workflow on the selected documents."
        ),
        .workflowLangGraphPreview: .init(
            name: "Workflow LangGraph preview",
            tier: .dev,
            swiftFlag: "fichero.features.workflow_langgraph_preview",
            uxGroup: "Processing",
            notes: "Inspect the compiled LangGraph form of a workflow."
        ),
        .batches: .init(
            name: "Batches",
            tier: .beta,
            swiftFlag: "fichero.features.batches",
            uxGroup: "Processing",
            notes: "Queue workflow work across many documents."
        ),
        .workflowToolsFiles: .init(
            name: "Workflow tools files",
            tier: .beta,
            swiftFlag: "fichero.features.workflow_tools_files",
            uxGroup: "Processing",
            notes: "File and collection tools enabled in shipped workflows."
        ),
        .knowledgeGraph: .init(
            name: "Knowledge graph",
            tier: .beta,
            swiftFlag: "fichero.features.knowledge_graph",
            uxGroup: "Knowledge",
            notes: "Entities, claims, provenance, and ontology surfaces."
        ),
        .curation: .init(
            name: "Curation",
            tier: .beta,
            swiftFlag: nil,
            uxGroup: "Knowledge",
            notes: "Persist corrections as rules that future imports obey."
        ),
        .providers: .init(
            name: "Providers",
            tier: .beta,
            swiftFlag: nil,
            uxGroup: "Models",
            notes: "Local and cloud model providers plus model catalog."
        ),
        .modelComparison: .init(
            name: "Model comparison",
            tier: .beta,
            swiftFlag: nil,
            uxGroup: "Models",
            notes: "Compare model behavior and metadata in-app."
        ),
        .cli: .init(
            name: "CLI",
            tier: .beta,
            swiftFlag: nil,
            uxGroup: "Clients",
            notes: "Typed CLI over the same HTTP API surface."
        ),
        .mcpServer: .init(
            name: "MCP server",
            tier: .beta,
            swiftFlag: nil,
            uxGroup: "Clients",
            notes: "MCP server surface backed by the engine."
        ),
        .activity: .init(
            name: "Activity",
            tier: .beta,
            swiftFlag: "fichero.features.activity",
            uxGroup: "Processing",
            notes: "Execution history and live progress over SSE."
        ),
        .research: .init(
            name: "Research",
            tier: .beta,
            swiftFlag: "fichero.features.research",
            uxGroup: "Knowledge",
            notes: "KG-backed research workflows and answer surface."
        ),
        .settingsGeneralTab: .init(
            name: "Settings general tab",
            tier: .beta,
            swiftFlag: "fichero.features.settings_general_tab",
            uxGroup: "Settings",
            notes: "General settings panel."
        ),
        .settingsEngineTab: .init(
            name: "Settings engine tab",
            tier: .dev,
            swiftFlag: "fichero.features.settings_engine_tab",
            uxGroup: "Settings",
            notes: "Engine settings panel."
        ),
        .settingsShareTab: .init(
            name: "Settings share tab",
            tier: .dev,
            swiftFlag: "fichero.features.settings_share_tab",
            uxGroup: "Settings",
            notes: "Sharing and collaboration settings panel."
        ),
        .settingsUsersTab: .init(
            name: "Settings users tab",
            tier: .dev,
            swiftFlag: "fichero.features.settings_users_tab",
            uxGroup: "Settings",
            notes: "Multi-user settings panel."
        ),
        .settingsCaptureTab: .init(
            name: "Settings capture tab",
            tier: .dev,
            swiftFlag: "fichero.features.settings_capture_tab",
            uxGroup: "Settings",
            notes: "Capture and intake settings panel."
        ),
        .chat: .init(
            name: "Chat",
            tier: .beta,
            swiftFlag: "fichero.features.chat",
            uxGroup: "Knowledge",
            notes: "RAG conversation over the active library."
        ),
        .workflowToolsSearch: .init(
            name: "Workflow tools search",
            tier: .dev,
            swiftFlag: "fichero.features.workflow_tools_search",
            uxGroup: "Processing",
            notes: "Search-oriented workflow tools that are not yet shipped by default."
        ),
        .workflowToolsTransform: .init(
            name: "Workflow tools transform",
            tier: .dev,
            swiftFlag: "fichero.features.workflow_tools_transform",
            uxGroup: "Processing",
            notes: "Transform workflow tools still under review."
        ),
        .workflowToolsConvert: .init(
            name: "Workflow tools convert",
            tier: .dev,
            swiftFlag: "fichero.features.workflow_tools_convert",
            uxGroup: "Processing",
            notes: "Convert workflow tools still under review."
        ),
        .workflowToolsLogic: .init(
            name: "Workflow tools logic",
            tier: .dev,
            swiftFlag: "fichero.features.workflow_tools_logic",
            uxGroup: "Processing",
            notes: "Logic workflow tools still under review."
        ),
        .workflowToolsOutputs: .init(
            name: "Workflow tools outputs",
            tier: .dev,
            swiftFlag: "fichero.features.workflow_tools_outputs",
            uxGroup: "Processing",
            notes: "Output workflow tools still under review."
        ),
        .workflowToolsAudio: .init(
            name: "Workflow tools audio",
            tier: .dev,
            swiftFlag: "fichero.features.workflow_tools_audio",
            uxGroup: "Processing",
            notes: "Audio workflow tools still under review."
        ),
        .workflowToolsVideo: .init(
            name: "Workflow tools video",
            tier: .dev,
            swiftFlag: "fichero.features.workflow_tools_video",
            uxGroup: "Processing",
            notes: "Video workflow tools still under review."
        ),
        .workflowToolsMcp: .init(
            name: "Workflow tools MCP",
            tier: .dev,
            swiftFlag: "fichero.features.workflow_tools_mcp",
            uxGroup: "Processing",
            notes: "MCP-backed workflow tools still under review."
        ),
        .workflowToolsAgents: .init(
            name: "Workflow tools agents",
            tier: .dev,
            swiftFlag: "fichero.features.workflow_tools_agents",
            uxGroup: "Processing",
            notes: "Agent-backed workflow tools still under review."
        ),
        .providersExtended: .init(
            name: "Extended provider catalog",
            tier: .dev,
            swiftFlag: "fichero.features.providers_extended",
            uxGroup: "Models",
            notes: "Expanded provider and model catalog beyond the shipped baseline."
        ),
        .settingsBackendTab: .init(
            name: "Settings backend tab",
            tier: .dev,
            swiftFlag: "fichero.features.settings_backend_tab",
            uxGroup: "Settings",
            notes: "Backend configuration panel."
        ),
        .settingsModelsTab: .init(
            name: "Settings models tab",
            tier: .dev,
            swiftFlag: "fichero.features.settings_models_tab",
            uxGroup: "Settings",
            notes: "Model configuration panel."
        ),
        .libraryFilterToolbar: .init(
            name: "Library filter toolbar",
            tier: .dev,
            swiftFlag: "fichero.features.library_filter_toolbar",
            uxGroup: "Core",
            notes: "Advanced filter toolbar in the library."
        ),
        .librarySearchSplitLayouts: .init(
            name: "Library and search split layouts",
            tier: .dev,
            swiftFlag: "fichero.features.library_search_split_layouts",
            uxGroup: "Core",
            notes: "Split layouts for library and search."
        ),
        .claimHighlightSync: .init(
            name: "Claim highlight sync",
            tier: .dev,
            swiftFlag: "fichero.features.claim_highlight_sync",
            uxGroup: "Knowledge",
            notes: "Bidirectional claim highlight sync across panes."
        ),
        .pdfScrollGridSync: .init(
            name: "PDF scroll grid sync",
            tier: .dev,
            swiftFlag: "fichero.features.pdf_scroll_grid_sync",
            uxGroup: "Core",
            notes: "Live PDF scroll synchronization into other panes."
        ),
        .workspaceMode: .init(
            name: "Workspace mode",
            tier: .dev,
            swiftFlag: "fichero.features.workspace_mode",
            uxGroup: "Clients",
            notes: "Alternate workspace-oriented shell mode."
        ),
        .spatialMode: .init(
            name: "Spatial mode",
            tier: .dev,
            swiftFlag: "fichero.features.spatial_mode",
            uxGroup: "Clients",
            notes: "Spatial library presentation mode."
        ),
        .canvasRealityKit2D: .init(
            name: "Canvas RealityKit 2D",
            tier: .dev,
            swiftFlag: "fichero.features.canvas_realitykit_2d",
            uxGroup: "Clients",
            notes: "Route the 2D canvas to the RealityKit renderer."
        ),
        .canvasRealityKit3D: .init(
            name: "Canvas RealityKit 3D",
            tier: .dev,
            swiftFlag: "fichero.features.canvas_realitykit_3d",
            uxGroup: "Clients",
            notes: "Route the 3D space to the contract-based RealityKit renderer."
        ),
        .automation: .init(
            name: "Automation",
            tier: .dev,
            swiftFlag: "fichero.features.automation",
            uxGroup: "Processing",
            notes: "Schedules, triggers, and automated flows."
        ),
        .mcpUi: .init(
            name: "MCP servers UI",
            tier: .dev,
            swiftFlag: "fichero.features.mcp",
            uxGroup: "Clients",
            notes: "UI for managing MCP server connections."
        ),
        .agents: .init(
            name: "Agents",
            tier: .dev,
            swiftFlag: "fichero.features.agents",
            uxGroup: "Knowledge",
            notes: "In-app agent surface still in the rawest stage."
        ),
        .integrations: .init(
            name: "Integrations",
            tier: .dev,
            swiftFlag: "fichero.features.integrations",
            uxGroup: "Clients",
            notes: "External integrations surface still in the rawest stage."
        ),
        .iiif: .init(
            name: "IIIF",
            tier: .dev,
            swiftFlag: nil,
            uxGroup: "Core",
            notes: "IIIF image and annotation server interoperability."
        )
    ]
}
// swiftlint:enable file_length
